### ISSUE TITLE
Regarding "My V3n0m-Scanner keeys stopping"

### ISSUE THREAD

**Issue by NovaCygni** [v3n0m-Scanner/V3n0M-Scanner#101]
In regard to the following, I amusingly will raise the following points:
https://www.nulled.to/topic/274858-my-v3n0m-scanner-keeps-freezing/

Point 1) Replacing the d0rk list with one designed to find credit card information or "shopping" sites likely to have them, will have obvious countermeasures in place, not to mention,
Point 2) When trying to work out why your scanner fails to continue you should consider what "Dork in progress" its currently "stopped" on... and the possible reasons why.
Point 3) That site is alot of the blind leading the blind, and nefarious content pushers, posting there and getting no responses is likely equally reflective as to the foolishness of this post in the first place, and the sort of "learning" can be acquired associating in those circles.
Point 4) Winblows :') Seriously, I mean, come on.... come on.... seriously....

**Comment by kattstof** [comment]
Well i mean, a skid could look at the 
/src/  and see the counter-measures in place. So,this question really illuminates mental capacity, or lack thereof. by the person asking.
