### ISSUE TITLE
issues with setup.py

### ISSUE THREAD

**Issue by mpkosewski** [v3n0m-Scanner/V3n0M-Scanner#102]
for whatever reason I can't get it to install. I've installed all the packages that should be required but still run into the same issue. 

Im on 4.12.0-kali1-amd64

here's my attempt installing:

root@evilkitty:~/Github/web# git clone https://github.com/v3n0m-Scanner/V3n0M-Scanner.git
Cloning into 'V3n0M-Scanner'...
remote: Counting objects: 1114, done.
remote: Total 1114 (delta 0), reused 0 (delta 0), pack-reused 1114
Receiving objects: 100% (1114/1114), 30.93 MiB | 2.68 MiB/s, done.
Resolving deltas: 100% (711/711), done.
root@evilkitty:~/Github/web# apt-get install python3-bs4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-bs4 is already the newest version (4.6.0-1).
python3-bs4 set to manually installed.
The following packages were automatically installed and are no longer required:
  libqgsttools-p1 libqt5multimedia5-plugins libqt5multimediawidgets5 libwireshark8 libwiretap6 libwsutil7
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
root@evilkitty:~/Github/web# apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libqgsttools-p1 libqt5multimedia5-plugins libqt5multimediawidgets5 libwireshark8 libwiretap6 libwsutil7
0 upgraded, 0 newly installed, 6 to remove and 8 not upgraded.
After this operation, 81.4 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 519945 files and directories currently installed.)
Removing libqt5multimedia5-plugins:amd64 (5.9.1-3) ...
Removing libqgsttools-p1:amd64 (5.9.1-3) ...
Removing libqt5multimediawidgets5:amd64 (5.9.1-3) ...
Removing libwireshark8:amd64 (2.2.7-1) ...
Removing libwiretap6:amd64 (2.2.7-1) ...
Removing libwsutil7:amd64 (2.2.7-1) ...
Processing triggers for libc-bin (2.24-14) ...
root@evilkitty:~/Github/web# cd V3n0M-Scanner/
root@evilkitty:~/Github/web/V3n0M-Scanner# ls
LICENSE  PKGBUILD  README.md  setup.py  src
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
creating build
creating build/lib
creating build/lib/v3n0m
copying src/v3n0m.py -> build/lib/v3n0m
copying src/cli.py -> build/lib/v3n0m
copying src/cloudbuster.py -> build/lib/v3n0m
copying src/buster.py -> build/lib/v3n0m
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
creating /root/.local/lib/python3.5/site-packages/v3n0m
copying build/lib/v3n0m/v3n0m.py -> /root/.local/lib/python3.5/site-packages/v3n0m
copying build/lib/v3n0m/cli.py -> /root/.local/lib/python3.5/site-packages/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> /root/.local/lib/python3.5/site-packages/v3n0m
copying build/lib/v3n0m/buster.py -> /root/.local/lib/python3.5/site-packages/v3n0m
byte-compiling /root/.local/lib/python3.5/site-packages/v3n0m/v3n0m.py to v3n0m.cpython-35.pyc
byte-compiling /root/.local/lib/python3.5/site-packages/v3n0m/cli.py to cli.cpython-35.pyc
byte-compiling /root/.local/lib/python3.5/site-packages/v3n0m/cloudbuster.py to cloudbuster.cpython-35.pyc
byte-compiling /root/.local/lib/python3.5/site-packages/v3n0m/buster.py to buster.cpython-35.pyc
running install_egg_info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# pip install -U setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
root@evilkitty:~/Github/web/V3n0M-Scanner# pip3 install -U setuptools
bash: pip3: command not found
root@evilkitty:~/Github/web/V3n0M-Scanner# pip3 install -U setuptools
Collecting setuptools
  Downloading setuptools-36.3.0-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 1.8MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 36.2.7
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed setuptools-36.3.0
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --help
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
Common commands: (see '--help-commands' for more)

  setup.py build      will build the package underneath 'build/'
  setup.py install    will install the package

Global options:
  --verbose (-v)  run verbosely (default)
  --quiet (-q)    run quietly (turns verbosity off)
  --dry-run (-n)  don't actually do anything
  --help (-h)     show detailed help message
  --no-user-cfg   ignore pydistutils.cfg in your home directory

Options for 'install' command:
  --prefix            installation prefix
  --exec-prefix       (Unix only) prefix for platform-specific files
  --home              (Unix only) home directory to install under
  --install-base      base installation directory (instead of --prefix or --
                      home)
  --install-platbase  base installation directory for platform-specific files
                      (instead of --exec-prefix or --home)
  --root              install everything relative to this alternate root
                      directory
  --install-purelib   installation directory for pure Python module
                      distributions
  --install-platlib   installation directory for non-pure module distributions
  --install-lib       installation directory for all module distributions
                      (overrides --install-purelib and --install-platlib)
  --install-headers   installation directory for C/C++ headers
  --install-scripts   installation directory for Python scripts
  --install-data      installation directory for data files
  --compile (-c)      compile .py to .pyc [default]
  --no-compile        don't compile .py files
  --optimize (-O)     also compile with optimization: -O1 for "python -O", -O2
                      for "python -OO", and -O0 to disable [default: -O0]
  --force (-f)        force installation (overwrite any existing files)
  --skip-build        skip rebuilding everything (for testing/debugging)
  --record            filename in which to record list of installed files
  --install-layout    installation layout to choose (known values: deb, unix)
  --user              install in user site-package
                      '/root/.local/lib/python3.5/site-packages'

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user --verbose
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# ls
build  LICENSE  PKGBUILD  README.md  setup.py  src
root@evilkitty:~/Github/web/V3n0M-Scanner# gedit README.md 
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user --verbose
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# ls src/
AnimatedDemo.gif  buster.py  cli.py  cloudbuster.py  desktop-menu  lists  modules  v3n0m.py
root@evilkitty:~/Github/web/V3n0M-Scanner# cd src/lists/
root@evilkitty:~/Github/web/V3n0M-Scanner/src/lists# python3.5 update.py 
Downloading https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "update.py", line 37, in <module>
    download(d[0], d[1], d[2])
  File "update.py", line 20, in download
    urllib.request.urlretrieve(url, file, progressbar)
  File "/usr/lib/python3.5/urllib/request.py", line 198, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'lists/ips-v4'
root@evilkitty:~/Github/web/V3n0M-Scanner/src/lists# python3.5 update.py 
Downloading https://www.cloudflare.com/ips-v4
Downloading https://www.cloudflare.com/ips-v6
Downloading http://crimeflare.net:82/domains/ipout.zip
100.0% 27541504 / 27537665
Traceback (most recent call last):
  File "update.py", line 39, in <module>
    unzip('lists/ipout')
  File "update.py", line 25, in unzip
    myzip.write(file)
  File "/usr/lib/python3.5/zipfile.py", line 1433, in write
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lists/ipout'
root@evilkitty:~/Github/web/V3n0M-Scanner/src/lists# python3.5 update.py 
Downloading https://www.cloudflare.com/ips-v4
Downloading https://www.cloudflare.com/ips-v6
Downloading http://crimeflare.net:82/domains/ipout.zip
 72.5% 19955712 / 27537665^CTraceback (most recent call last):
  File "update.py", line 37, in <module>
    download(d[0], d[1], d[2])
  File "update.py", line 20, in download
    urllib.request.urlretrieve(url, file, progressbar)
  File "/usr/lib/python3.5/urllib/request.py", line 217, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
root@evilkitty:~/Github/web/V3n0M-Scanner/src/lists# python3.5 update.py 
Downloading https://www.cloudflare.com/ips-v4
Downloading https://www.cloudflare.com/ips-v6
Downloading http://crimeflare.net:82/domains/ipout.zip
100.0% 27541504 / 27537665
Everything up to date!
root@evilkitty:~/Github/web/V3n0M-Scanner/src/lists# cd ..
root@evilkitty:~/Github/web/V3n0M-Scanner/src# cd ..
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3.5 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3.5 setup.py install 
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
creating /usr/local/lib/python3.5/dist-packages/v3n0m
copying build/lib/v3n0m/v3n0m.py -> /usr/local/lib/python3.5/dist-packages/v3n0m
copying build/lib/v3n0m/cli.py -> /usr/local/lib/python3.5/dist-packages/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> /usr/local/lib/python3.5/dist-packages/v3n0m
copying build/lib/v3n0m/buster.py -> /usr/local/lib/python3.5/dist-packages/v3n0m
byte-compiling /usr/local/lib/python3.5/dist-packages/v3n0m/v3n0m.py to v3n0m.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/v3n0m/cli.py to cli.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/v3n0m/cloudbuster.py to cloudbuster.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/dist-packages/v3n0m/buster.py to buster.cpython-35.pyc
running install_egg_info
Writing /usr/local/lib/python3.5/dist-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# pip
pip      pip2     pip3     pipal    pipetty  
root@evilkitty:~/Github/web/V3n0M-Scanner# pip3 install -U setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages
root@evilkitty:~/Github/web/V3n0M-Scanner# pip3 search distutils
ADIVINA_EL_NUMERO (0.1)                    - Ejemplo del funcionamiento de distutils
Aplicacion-de-ejemplo (0.1)                - Ejemplo del funcionamiento de distutils
bdist-venv2 (0.1.3)                        - Python distutils extension to create virtualenv built distributions.
bdist_docker (0.1.1)                       - Distutils extension command to build docker images for python applications.
bdist_mpkg (0.5.0)                         - Builds Mac OS X installer packages from distutils
bdist_venv (0.1.2)                         - Python distutils extension to bundle package as a virtualenv.
bitbucket-distutils (0.1.2)                - Distribute/setuptools/distutils command for Bitbucket. You can use Bitbucket downloads instead of PyPI downloads for release.
buildutils (0.3)                           - Distutils extensions for developing Python libraries and applications.
reahl-bzrsupport (3.2.0)                   - Distutils support for Bazaar when using Reahl development tools.
collective.checkdocs (0.2)                 - Distutils command to view and validate restructured text in package's long_description
collective.dist (0.2.5)                    - Distutils commands to upload files to several servers
collective.recipe.distutils (0.1)          - A buildout recipe to install distutils Python packages.
Cpyx (0.2.2.0)                             - gcc/cython/distutils wrapper for compiling Cython and C code directly from python
d2to1 (0.2.12.post1)                       - Allows using distutils2-like setup.cfg files for a package's metadata with a distribute/setuptools setup.py
jdhp-distutils-demo (0.2)                  - A snippet to test distutils and PyPI
ploneconf-demo (1.0)                       - demo of distutils for the plone conf -- will be removed from PyPI after the tutorial
DistChecker (1.0)                          - Helper utiltiies for distutils such as checking the sanity of an sdist
distcontrib (0.1.0)                        - Contributions to Distutils
distcontrib-migrate (0.1.1)                - Contributions to Distutils
distext (0.0.4)                            - Silveregg distutils extensions
distPND (0.1)                              - Extensions to Python's Distutils to build PND files
distutilazy (0.4.2)                        - Extra distutils commands
distutils-pytest (0.1)                     - Call pytest from a distutils setup.py script.
distutils-licenses (0.1.2)                 - adds a command to setup.py to list licenses of packages
github-distutils (0.1.1)                   - Distribute/setuptools/distutils command for GitHub. You can use GitHub downloads instead of PyPI downloads for release.
pyqt-distutils (0.7.3)                     - A set of distutils extension for building Qt ui files
Distutils2-py3 (1.0a5.dev0)                - Python Packaging Library
Distutils2 (1.0a4)                         - Python Packaging Library
distutils644 (0.1)                         - sanitize ownership, permissions and tar format in distutils-generated tarballs
distutils_build_without_typehints (0.6.1)  - A build command that strips typehints from the code during the build.
distutils_ui (0.1.2)                       - A distutils build extension for PyQt{4,5} applications
distutilscross (0.1)                       - Cross Compile Python Extensions
doublespeak (0.3)                          - Babel/distutils commands to help with managing Javascript translations.
rust-ext (0.1)                             - Distutils helpers for rust Python extensions
foobar2 (0.1)                              - A hello-world of distutils
hello_hepeng (1.0.0)                       - Distutils hello distribution #1
innosetup (0.6.9)                          - distutils extension module - create an installer by InnoSetup.
iw.dist (0.1.8)                            - Distutils commands to upload files to several servers
lpdistutils (0.1)                          - Distutils commands for working with Launchpad and Bazaar.
mete0r.distutils.virtualenv (0.0.3)        - Manage virtualenvs with requirement files
minify (0.1.4)                             - Minify provides distutils/setuptools commands for minifying CSS and JS resources
numscons (0.12.0)                          - Enable to use scons within distutils to build extensions
orchdist (0.1.0.dev1)                      - A python module for executing ``distutils`` commands in concurrency
pip2 (0.0.1.dev1)                          - Experimental port of pip to use distutils2.
pyp-sandbox (7abc960)                      - Test package for distutils/setuptools/pbr experimentation.
pytest-runner (2.11.1)                     - Invoke py.test as distutils command with dependency resolution
pyverify (0.8.1)                           - Verify python distributions. Requires Distutils2
requiresexample (0.1.1)                    - An example package to demonstrate the use of `requires` in pure distutils
sample_distutils2_project (1.1.0)          - Sample Distutils2 Project
setupfiles (0.0.50)                        - distutils/setuptools replacement
stsci.distutils (0.3.7)                    - distutils/packaging-related utilities used by some of STScI's packages
testerz (0.0.1)                            - Sample module to test Python distutils
verlib (0.1)                               - A new version comparison tool for distutils.
xdistutils (0.2.0)                         - provide useful distutils commands
zerokspot.recipe.distutils (0.1.2)         - Recipe for zc.buildout that downloads one or multiple distutils-archives and installs them
root@evilkitty:~/Github/web/V3n0M-Scanner# pip install Distutils2-py3 
Collecting Distutils2-py3
  Downloading Distutils2-py3-1.0a5.dev0.tar.gz (881kB)
    100% |████████████████████████████████| 890kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tq3gto/Distutils2-py3/setup.py", line 74, in <module>
        setup_kwargs = cfg_to_args('setup.cfg')
      File "/tmp/pip-build-tq3gto/Distutils2-py3/setup.py", line 44, in cfg_to_args
        with open(path, encoding='utf-8') as fp:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tq3gto/Distutils2-py3/
root@evilkitty:~/Github/web/V3n0M-Scanner# pip3 install Distutils2-py3 
Collecting Distutils2-py3
  Using cached Distutils2-py3-1.0a5.dev0.tar.gz
Building wheels for collected packages: Distutils2-py3
  Running setup.py bdist_wheel for Distutils2-py3 ... done
  Stored in directory: /root/.cache/pip/wheels/6b/80/f5/6173155de83733c10b1a709ca6e14b40ab95a5a8265dfba71f
Successfully built Distutils2-py3
Installing collected packages: Distutils2-py3
Successfully installed Distutils2-py3-1.0a5.dev0
root@evilkitty:~/Github/web/V3n0M-Scanner# python3.5 setup.py install 
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.5/dist-packages/V3n0M-418.egg-info
Writing /usr/local/lib/python3.5/dist-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3.5 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3.6 setup.py install --user
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
creating /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/v3n0m.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/cli.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/buster.py -> /root/.local/lib/python3.6/site-packages/v3n0m
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/v3n0m.py to v3n0m.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/cli.py to cli.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/cloudbuster.py to cloudbuster.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/buster.py to buster.cpython-36.pyc
running install_egg_info
Writing /root/.local/lib/python3.6/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
Writing /root/.local/lib/python3.5/site-packages/V3n0M-418.egg-info
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install --root
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --root requires argument
root@evilkitty:~/Github/web/V3n0M-Scanner# python3 setup.py install 
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.5/dist-packages/V3n0M-418.egg-info
Writing /usr/local/lib/python3.5/dist-packages/V3n0M-418.egg-info

**Comment by mpkosewski** [comment]
however I just randomly tried executing the venom file and it seems to kinda work? this what I got when trying to run the update from option 7;:


[1] Skip to custom SQLi list checking
[2] Print contents of Log files
[3] Flush Cache and Delete Logs *Warning will erase Toxin Logs/Saves aswell* 
[4] Perform forced update of ALL installed Python packages and dependancies on system
[0] Return to main menu
:4
This will install the missing modules and upgrade them to current versions then update your Python3 entirely
You will have 10 seconds to cancel this action before the system begins
sudo is required as these changes are systemwide upgrades/updates for Python
Requirement already up-to-date: Distutils2-py3 in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: markerlib in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: V3n0M in /root/.local/lib/python3.5/site-packages

**Comment by NovaCygni** [comment]
edit the line in the setup.py that says "install_requires" and change it to just "requires".  Next update will have a fallback setup.py so I can better automate support across platforms.

**Comment by mpkosewski** [comment]
Nice! I'll give it a shot today and see what happens. I had some issues running it but worst case I'll try a fresh install with these changes :)

**Comment by mpkosewski** [comment]
Ok so I gave it a try and here is what it gave me in return:

`~/Github/web/V3n0M-Scanner# python3 setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    'pip', 'dnspython', 'tqdm', 'aioftp']
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.5/distutils/dist.py", line 1208, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.5/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-branch'
`

**Comment by mpkosewski** [comment]
It looks like its related to https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/47
