### ISSUE TITLE
Python error [windows]

### ISSUE THREAD

**Issue by suyashwon** [v3n0m-Scanner/V3n0M-Scanner#106]
Whenever i run it
Python v3n0m.py it shows this
c:\venom\src>python v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----|

 Exception Error Message encountered: <class 'Exception'>

|--- You are advised to run either or both steps below   ---|
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---|
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --|
| --Note, Requires Sudo or Root to perform updates/fixes to Python

             V3n0M python modules can be updated with either option below
[1] Run Pip3 and Auto-Update Python3 modules to latest versions,
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit

Please help it would be appreciated

**Comment by kattstof** [comment]
Install them manually using pip

**Comment by suyashwon** [comment]
Can u provide command to use?? I am still noob in this things
