### ISSUE TITLE
Pip3 problem

### ISSUE THREAD

**Issue by suyashwon** [v3n0m-Scanner/V3n0M-Scanner#108]
I get this erorr while installing aiohttp
c:\v3n0m\src>pip3 install aiohttp httplib2 socksipy-branch requests dns url
Collecting aiohttp
  Downloading aiohttp-2.2.5-cp35-cp35m-win_amd64.whl (318kB)
    100% |################################| 327kB 2.6MB/s
Collecting httplib2
  Using cached httplib2-0.10.3.tar.gz
Collecting socksipy-branch
  Using cached SocksiPy-branch-1.01.tar.gz
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns

**Comment by NovaCygni** [comment]
Change dns to dnspython.
