### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by github00711** [v3n0m-Scanner/V3n0M-Scanner#111]
after a scan when try importing into a file, mostly euro site:

Traceback (most recent call last):
  File "v3n0m.py", line 1215, in <module>
    fmenu()
  File "v3n0m.py", line 993, in fmenu
    fscan()
  File "v3n0m.py", line 672, in fscan
    vulnscan()
  File "v3n0m.py", line 763, in vulnscan
    list_name.write(t + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 65: ordinal not in range(128)

i am no programmer unfortunately.

i found this might help, but I have no idea how to implement:

https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by NovaCygni** [comment]
OS in use? Likely a easy fix anyway its just been lazyness on my part but never seen this issue before :/

**Comment by github00711** [comment]
Ubuntu 16.04

**Comment by kattstof** [comment]
Never seen this happen before but it looks similar to an old bug. Try this:
 go to python3's client.py nano into it and change everything that says ascii to utf-8 and maxheaders to 10000
Let me know if it works

**Comment by NovaCygni** [comment]
Technically it was me being lazy, I knew not allowing the user to change iso types could be a issue, just first time its happened in years, I can probably throw in a "Internal Settings" option in the sub-menu, likely anyone with non-utf-8 will have this issue so I suppose itd be the best option really. Will leave thread open to remind me to fix it next update.

**Comment by NovaCygni** [comment]
Should be fixed at next Patch update,
