### ISSUE TITLE
Unknown distribution option: 'install_requires'

### ISSUE THREAD

**Issue by rohitsharma36** [v3n0m-Scanner/V3n0M-Scanner#113]
python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
creating /usr/local/lib/python2.7/dist-packages/v3n0m
copying build/lib.linux-x86_64-2.7/v3n0m/v3n0m.py -> /usr/local/lib/python2.7/dist-packages/v3n0m
copying build/lib.linux-x86_64-2.7/v3n0m/cloudbuster.py -> /usr/local/lib/python2.7/dist-packages/v3n0m
copying build/lib.linux-x86_64-2.7/v3n0m/lfisuite.py -> /usr/local/lib/python2.7/dist-packages/v3n0m
byte-compiling /usr/local/lib/python2.7/dist-packages/v3n0m/v3n0m.py to v3n0m.pyc
  File "/usr/local/lib/python2.7/dist-packages/v3n0m/v3n0m.py", line 514
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python2.7/dist-packages/v3n0m/cloudbuster.py to cloudbuster.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/v3n0m/lfisuite.py to lfisuite.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/V3n0M-419.egg-info

While Running setup.py 
python setup.py

 UserWarning: Unknown distribution option: 'install_requires'

  warnings.warn(msg)

OS : kali 2017.2

**Comment by rohitsharma36** [comment]
![screenshot from 2017-10-08 14-56-08](https://user-images.githubusercontent.com/12293659/31315601-3fb03368-ac39-11e7-9fa7-b68dda6d19b6.png)

**Comment by NovaCygni** [comment]
Tip1: Your system Python should be Python3 not Python2, you can create a quick symlink to change it, your calling "Python" which will on shitty Kali, default to Python2 not Python3.
Tip2: If you cant be asked to change the default symlink you can manually specify Python version with ie, python3 v3n0m
Tip3: sudo will help ;)
