### ISSUE TITLE
Error when Launching + Can't create Launcher for it

### ISSUE THREAD

**Issue by catest0** [v3n0m-Scanner/V3n0M-Scanner#115]
Hi, i used v3n0m before, amazing work thanks. But now, i download it from github, follow the install guide, the problems are : 

It does not create a Launcher in PATH
It fails at launching when i go to /src and use "python3 v3n0m.py", i'm on Kali Linux Light right now. The error =>  **|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: <class 'Exception'>
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date**

Now whether i choose [1] or [2] i get an error, i have python 2.7 and 3.6 installed. Error when using [1] =>
**/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
Traceback (most recent call last):
  File "v3n0m.py", line 1288, in <module>
    codecs.lookup('mbcs')
NameError: name 'codecs' is not defined** 

Error when using [2] => **/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
Traceback (most recent call last):
  File "v3n0m.py", line 1288, in <module>
    codecs.lookup('mbcs')
NameError: name 'codecs' is not defined**

I don't know if the way to solve it is obvious, but i'm sure it comes from me since no one complains about that, i would very much appreciate your help though, thanks again for the nice tool.

**Comment by NovaCygni** [comment]
Try "python3.6 -m pip install --upgrade pip setuptools wheel" and if no joy quickly edit the v3n0m.py file and change the lines that say pip3.6 to just be pip3

**Comment by catest0** [comment]
hi, thanks for the answer, i was wrong, i have python 3.7, still did what you said though with python3.7, still have same errors, and about tarball i dont need because i have latest pip 9.

**Comment by NovaCygni** [comment]
Ah then you should be fine to change the relative lines to just "pip", dont use Kali myself but basically the error is saying it cant find the command pip.

**Comment by catest0** [comment]
I still get errors, seems Kali doesnt like when i install from git, but apt is so bad and they dont update' i really want to use v3n0m though' do you mind telling me what distro you use ? im thinking of going on Linux from Scratch if i dont find a distro that support anything you throw at it...

**Comment by NovaCygni** [comment]
Blackarch Linux, Kali is for n00blets and for sticking on a USB stick for emergency "On-Call" jobs...
Your best of download the ISO for "Archlinux Anywhere" and using that to do the install (* when it fails to connect to the wireless network, retry it its just a bug where it doesnt connect first time *), Once archlinux is installed you can upgrade it to BlackArch linux by following the steps on the Blackarch website. 
A couple advanced tools manually require setting up, as they should (* Kali and its preloaded credentials for the tools :') So `secure`  xD *)

(* Btw gathering this failed for you? ---> apt-get install python3-dev apt-get install python-dev *)

**Comment by catest0** [comment]
youre cool NovaCygni, thanks will do that, and i totally agree with you kali really was getting on my nerves...

**Comment by NovaCygni** [comment]
Your best of  doing:
Archlinux install with Archlinux anywhere iso (* when offered shell choices select zsh ;) handy for tab autocomplete and much more *)
Adding Blackarch repo's as described in the blackarch download page
Enable yaourt/AUR Repos on your archlinux. 

BlackArch is basically a professional pentesters entire toolkit, far larger than Kalis junk, and very well maintained, you can stick to downloading tools via Github itself, but the BlackArch tools are github sources mostly anyway ;)  just any issues with tools are pre-fixed, ie, BEEF, Burpsuite, ZAP and many others have had minor and major issues resolved :)

**Comment by catest0** [comment]
Thanks again, doing all the steps you told me, you greatly helped me, archlinux seems like the distro for me.  

A tip from me now, want to help too heh, what i do for my tools instead of using repository is i downloaded the pentesting framework from TrustedSec, deleted all the modules inside, and added all that i use, made the launcher etc, so i can find the files easily, update them by categories or individually or all in a single command, and its near totally compatible on any unix distro, PTF really is crazy good, check it if you never did. And when you want a new tool, just add it to the modules and its there, always easily updated and working (i also do that for python,ruby,perl, everything i can so i have the edge).

**Comment by NovaCygni** [comment]
`pip3.6 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3.6 install -U`
Bit of Bash magic to make sure that everything remotely Python, is literally "Bleeding Edge" updated and up to date... hence why after a successful recovery menu launch its also one of the commands to be run by v3n0m, cause, you know, why would I want people whining about why Python 3.2 "Iz r not work for me" :')

**Comment by catest0** [comment]
ah, im newb on linux so i didnt know about commands like that, thanks for the tip.

**Comment by catest0** [comment]
Works perfectly, it even did a swap/root/tmp encryption, which saves me a lot of time, and works very well and so fast and light, cant thank you enough...
