### ISSUE TITLE
/bin/sh: 1: pip3.6: not found      when launching [1] and [2] of the first launch menu.

### ISSUE THREAD

**Issue by cegi** [v3n0m-Scanner/V3n0M-Scanner#116]
Hi, i liked very much your tool while i on BlackArch, but right now out of curiosity i'm on Kali and your tool is one of the few i can't make work. I did everything as said in your steps but there is this problem, first i get the error and the menu appears with the two choices to repair python and pip, and when i choose one of them i get : 
/bin/sh: 1: pip3.6: not found
/bin/sh: 1: pip3.6: not found
xargs: pip3.6: No such file or directory
Traceback (most recent call last):
  File "v3n0m.py", line 1288, in <module>
    codecs.lookup('mbcs')
NameError: name 'codecs' is not defined

I see only one problem in that, i have python3 and python2, pip3 and pip2 installed, i can install any tool that requires python3, the problem is that Kali uses pip2 and python2 as main Pip install, since your script use the main pip, it doesn't fine pip3, so if you could add to your tool a "requirements.txt" file so people not on BlackArch can also install it, would be great. Every tools that use python3 i could install them without problems as long as they had a requirements.txt file. Now if you have another solution to this i'm open of course, thanks.

Edit : Forgot to add, i also tried it on Gentoo and Ubuntu, had the exact same problems, so a requirements.txt seems to be the perfect solution.

Edit 2 : I have to also ask you what terminal config you are using on the preview, best terminal i ever seen, fit well with any colors and icons...

**Comment by NovaCygni** [comment]
This issue is because of this https://github.com/v3n0m-Scanner/V3n0M-Scanner/pull/112 no problem though ill remove it next push, knew that it isnt smart to use anything other than pip3 (* or pip itself if yourve made Python3 the default Python ;) *)
Terminal is Terminology, also "Requirements.txt" isnt required just check the setup.py

**Comment by cegi** [comment]
Thanks, really appreciated.

**Comment by NovaCygni** [comment]
If you have any rush to use v3n0m if you look at the code changes he submitted itll show you "Before/After", just change back what he changed in the v3n0m.py file and itll work fine.

**Comment by cegi** [comment]
As you said, it works when modifying the "setup.py file, thanks.

**Comment by NovaCygni** [comment]
pip3 is fine if i remember right its what I used before anyway.
