### ISSUE TITLE
Syntax error during installing setup.py

### ISSUE THREAD

**Issue by All3xJ** [v3n0m-Scanner/V3n0M-Scanner#117]
V3n0M-Scanner# python3 setup.py install --user
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
byte-compiling /root/.local/lib/python3.4/site-packages/v3n0m/v3n0m.py to v3n0m.cpython-34.pyc
  File "/root/.local/lib/python3.4/site-packages/v3n0m/v3n0m.py", line 997
    async def search(pages_pulled_as_one):
            ^
SyntaxError: invalid syntax

running install_egg_info
Removing /root/.local/lib/python3.4/site-packages/V3n0M-421.egg-info
Writing /root/.local/lib/python3.4/site-packages/V3n0M-421.egg-info

I'm using Debian 8

**Comment by NovaCygni** [comment]
Your running Python 3.4 not Python 3.6 ;) Please update your Python install to Python 3.6 :) V3n0M runs fine on debian so once thats done you should have no issues (* Though would benefit greatly once V3n0m is installed, to start it, select "Misc Options", then "Perform forced update"...... itll bring everything Pytnon on your system up to date with the latest versions. :+1:

**Comment by All3xJ** [comment]
It works, thanks!!
