### ISSUE TITLE
Error with setup

### ISSUE THREAD

**Issue by ib157** [v3n0m-Scanner/V3n0M-Scanner#118]
Ubuntu 16.04
Python 3.6
pip 9 
||INPUT||
python3.6 setup.py install --user

||OUTPUT||
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /home/igor/.local/lib/python3.6/site-packages/V3n0M-421.egg-info
Writing /home/igor/.local/lib/python3.6/site-packages/V3n0M-421.egg-info

**Comment by NovaCygni** [comment]
sudo apt-get install python-distutils
Gonna take a stab and say, Kali? Anyhows the issues just your missing some basic Python packages...
