### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by sandman4812av** [v3n0m-Scanner/V3n0M-Scanner#119]
when running gives me that error
i did 1 and 2 upgrade but can't fix it

Traceback (most recent call last):
  File "v3n0m.py", line 1335, in <module>
    fmenu()
  File "v3n0m.py", line 1096, in fmenu
    logo()
  File "v3n0m.py", line 79, in logo
    cache_Check()
  File "v3n0m.py", line 1297, in cache_Check
    my_file1 = Path("v3n0m-lfi.txt")
NameError: name 'Path' is not defined

**Comment by NovaCygni** [comment]
Please post the entire traceback, as it is what yourve posted provides no information at all.... path is, quite clearly, defined.... Post the entire traceback, or at least elaborate on your scenerio... considering as it is that message for want of a better word, is, clearly bullshit.

**Comment by sandman4812av** [comment]
cd src
python3 v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: <class 'Exception'>
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:
pressed 1 and it gives me error

Traceback (most recent call last):
  File "v3n0m.py", line 1335, in <module>
    fmenu()
  File "v3n0m.py", line 1096, in fmenu
    logo()
  File "v3n0m.py", line 79, in logo
    cache_Check()
  File "v3n0m.py", line 1297, in cache_Check
    my_file1 = Path("v3n0m-lfi.txt")
NameError: name 'Path' is not defined

**Comment by NovaCygni** [comment]
1) Python version installed on system?
2) OS in Use... 
3)... in future learn how to submit bug reports, your posts have been incredibly lacking in information... actually provide information about your system/scenario or frankly its impossible to tell you what your doing wrong (* likely, missing packages... *)
