### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by nekromoff** [v3n0m-Scanner/V3n0M-Scanner#122]
```
:~$ python ~/.local/lib/python3.6/site-packages/V3n0M-422-py3.6.egg/v3n0m/v3n0m.py 
  File "/home/XXXX/.local/lib/python3.6/site-packages/V3n0M-422-py3.6.egg/v3n0m/v3n0m.py", line 629
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax
:~$ sudo apt-get install python3-bs4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-bs4 is already the newest version (4.6.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


:~$ python3 ~/.local/lib/python3.6/site-packages/V3n0M-422-py3.6.egg/v3n0m/v3n0m.py 
Traceback (most recent call last):
  File "/home/XXXXXX/.local/lib/python3.6/site-packages/V3n0M-422-py3.6.egg/v3n0m/v3n0m.py", line 1219, in <module>
    d0rk = [line.strip() for line in open("lists/d0rks", 'r', encoding='utf-8')]
FileNotFoundError: [Errno 2] No such file or directory: 'lists/d0rks'
```

**Comment by NovaCygni** [comment]
Try extracting the entire V3n0m folder.. v3n0m.py should be in the same folder as a folder called "lists" with the file called "dorks" in it.

**Comment by NovaCygni** [comment]
Oh btw you might want to either CD to the directory the main v3n0m.py file is in, or actually run the setup.py and then just call v3n0m by typing v3n0m in terminal anywhere... not sure how I missed you were running it from the wrong location earlier.

**Comment by nekromoff** [comment]
It wasn't working installing via setup.py (this worked) and then directly
calling v3n0m (this did not), but never mind.

**Comment by NovaCygni** [comment]
open a terminal in the directory with the v3n0m.py file or cd to that files directory and run it from there, no idea why your not able to call the v3n0m script with just v3n0m being typed.
