### ISSUE TITLE
Sqli scanning halts (mostly)

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#123]
sqli scanning (option 1 and 2) after dorking halts on bigger scans not sure the cause of this but with big scans it completely breaks where as smaller scans it doesn't

**Comment by NovaCygni** [comment]
Will have a look later its like something simple like a site refusing to reply.

**Comment by kattstof** [comment]
i assumed it would be a 404'd page or it spewing not targeted domains (like the bug i mentioned awhile ago) and said not targeted domains might be messing up the search_ignore but search_ignore only seems to halt dorking? As changing my proxy while it halts makes it skip the current site and move onto the next fixing whats causing it to halt until it halts again then switching proxy mid scan fixes it again etc
in any case , cheers mate!

**Comment by NovaCygni** [comment]
Should be fixed, was missing: `timeout=3`

**Comment by kattstof** [comment]
ah i was thinking urllib.httperror exception but this works 
cheers!
