### ISSUE TITLE
Can't scan urls for sql injection 

### ISSUE THREAD

**Issue by Merujan99** [v3n0m-Scanner/V3n0M-Scanner#13]
![screenshot from 2016-01-01 13 28 27](https://cloud.githubusercontent.com/assets/4623322/12070395/2d934354-b083-11e5-808d-8f241744988b.png)

**Comment by NovaCygni** [comment]
thanks for bug report ill sort it now and reupload.

**Comment by NovaCygni** [comment]
Uploading Fix now.

**Comment by Merujan99** [comment]
thanks
