### ISSUE TITLE
tqdm problem (Not able to install)

### ISSUE THREAD

**Issue by onemoreplays** [v3n0m-Scanner/V3n0M-Scanner#133]
Hey,
so I have problem with tqdm (I everytime end with error).
Here is screen how it looks
![image](https://user-images.githubusercontent.com/29712695/36922591-abd9ae9c-1e68-11e8-8293-1c8664694afe.png)
Hopefully it will help to solve it.
Have a nice day :D 

//EDIT
After installing tqdm manually, same problem was with aio_ping so I installed it manually too and rn I can launch :D

**Comment by onemoreplays** [comment]
Looks like I had problem with internet connection on VM side (idk why)

**Comment by Rev-lulz** [comment]
try pip3 command rather than pip
