### ISSUE TITLE
Need help installing V3nom!

### ISSUE THREAD

**Issue by Myers75** [v3n0m-Scanner/V3n0M-Scanner#134]
Hi

First of all I got to say I am more or less a linux noob. I installed v3nom on my oracle kali linux. Kali has 3 pythons installed, Default is 2.7 I think. What version must I install for v3nom to work? I tried installing version 3.4 from the movie at youtube but its not showing in my /usr/bin/python folder. Also can't install that dev packages cause it say it can't locate them. Can someone give me some tips to be able to install v3nom in kali? Thanks in advance

**Comment by Rev-lulz** [comment]
sudo apt-get install python3-setuptools
sudo easy_install3 pip  

that should sort it

**Comment by Rev-lulz** [comment]
sudo apt-get install python3-dev && sudo apt-get install python-dev
