### ISSUE TITLE
v3n0m setup.py problem

### ISSUE THREAD

**Issue by dimdimak1** [v3n0m-Scanner/V3n0M-Scanner#135]
running install
running bdist_egg
running egg_info
writing V3n0M.egg-info\PKG-INFO
writing dependency_links to V3n0M.egg-info\dependency_links.txt
writing requirements to V3n0M.egg-info\requires.txt
writing top-level names to V3n0M.egg-info\top_level.txt
package init file 'src\__init__.py' not found (or not a regular file)
reading manifest file 'V3n0M.egg-info\SOURCES.txt'
writing manifest file 'V3n0M.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\v3n0m
copying build\lib\v3n0m\cloudbuster.py -> build\bdist.win32\egg\v3n0m
copying build\lib\v3n0m\lfisuite.py -> build\bdist.win32\egg\v3n0m
copying build\lib\v3n0m\v3n0m.py -> build\bdist.win32\egg\v3n0m
byte-compiling build\bdist.win32\egg\v3n0m\cloudbuster.py to cloudbuster.cpython-36.pyc
byte-compiling build\bdist.win32\egg\v3n0m\lfisuite.py to lfisuite.cpython-36.pyc
byte-compiling build\bdist.win32\egg\v3n0m\v3n0m.py to v3n0m.cpython-36.pyc
creating build\bdist.win32\egg\EGG-INFO
copying V3n0M.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying V3n0M.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying V3n0M.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying V3n0M.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying V3n0M.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
v3n0m.__pycache__.v3n0m.cpython-36: module references __file__
creating 'dist\V3n0M-425-py3.6.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing V3n0M-425-py3.6.egg
removing 'c:\users\dimdimak1\appdata\roaming\python\python36\site-packages\V3n0M-425-py3.6.egg' (and everything under it)
creating c:\users\dimdimak1\appdata\roaming\python\python36\site-packages\V3n0M-425-py3.6.egg
Extracting V3n0M-425-py3.6.egg to c:\users\dimdimak1\appdata\roaming\python\python36\site-packages
V3n0M 425 is already the active version in easy-install.pth

Installed c:\users\dimdimak1\appdata\roaming\python\python36\site-packages\v3n0m-425-py3.6.egg
Processing dependencies for V3n0M==425
Searching for url
Reading https://pypi.python.org/simple/url/
Downloading https://pypi.python.org/packages/58/1d/492737ab1ed4ed33ce5bc00a54e92b6ad26aa793cceed097a7af389c22b3/url-0.4.2.tar.gz#md5=74c09a76a22e46b9f634ae5fb5fc715e
Best match: url 0.4.2
Processing url-0.4.2.tar.gz
Writing C:\Users\DIMDIM~1\AppData\Local\Temp\easy_install-sfgye_ep\url-0.4.2\setup.cfg
Running url-0.4.2\setup.py -q bdist_egg --dist-dir C:\Users\DIMDIM~1\AppData\Local\Temp\easy_install-sfgye_ep\url-0.4.2\egg-dist-tmp-u533dkt5
Building from C++
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I HAVE VISUAL C++ INSTALLED.

**Comment by NovaCygni** [comment]
Problem with your winblows not the tool, also, C++ isnt used its, Python...

**Comment by kattstof** [comment]
First and foremost, You shouldn't be using winblows to run a vulnerability scanner. That being said, the setup script is fairly optional, but tty doesn't work with windows. Remove the import tty line from v3n0m.py cd into /src/  and run it, and it will run, sort of, winblows has all sorts of compatibility issues. So at the very least, just use a VM.
