### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mayday77** [v3n0m-Scanner/V3n0M-Scanner#137]
root@kali:~/Downloads/V3n0M-Scanner/src# sudo python v3n0m.py 
  File "v3n0m.py", line 656
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax
root@kali:~/Downloads/V3n0M-Scanner/src# 

#####################################
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by NovaCygni** [comment]
Never get tired of Kali users trying to run before walking.... Kali is pigswill, issues not with V3n0M, its a $USER issue, namely,,, user is taking for granted "Python" will be Python3, as a respectable OS would use, but, not Kali... in Kali its Python2 garbage... So your trying to run a Python3 program with, Python2.

**Comment by NovaCygni** [comment]
Oh and dont run it as root..... ./facepalm
