### ISSUE TITLE
dorks and vuln scan

### ISSUE THREAD

**Issue by Thiploll** [v3n0m-Scanner/V3n0M-Scanner#138]
can you please make it auto save ?

**Comment by NovaCygni** [comment]
There is a autosave file when the scan is complete its in the v3n0m folder, itll be "v3n0m-sqli.txt"

**Comment by Thiploll** [comment]
!!! i mean while is it scanning if something goes wrong while im scanning all my stuff is just gone !
i close my putty i go back to check i do screen -r (screenname) and i see its stopped fine , i go check if it saved anything but nope ! everything gone !

**Comment by Thiploll** [comment]
i scanned twice all to see my urls gone ;(

**Comment by Thiploll** [comment]
btw im trying to scan 300k urls for vuln after dork scan

**Comment by NovaCygni** [comment]
Your scanning is stopping? You mean on the checking if SQLi checks after the main harvesting? Suppose I can add a option to dump logs in a ~/,v3n0m-logs folder if people want it but atm im now curious to your "Everything is gone", Found Vuln sites when the confirmation comes of X Vuln type should automatically be added to the Vulns Database.

**Comment by kattstof** [comment]
sounds like op edited the dork list for carding or other acts. That or his proxy/vpn connection is dropping but AFAIK a keep-alive function was added ~2 years ago for connection drops.

**Comment by NovaCygni** [comment]
Yeh tbh I know what site is pushing these turds, sadly I keep getting talked out of putting "Punishment" features in for attempted carders, you know, your generic Priv-Escalation to 'rm -rf /' loving... though originally that was a idea for os.detect"kali" feature but I may still add the anti carders play book.

**Comment by kattstof** [comment]
The only issue that would cause is arsehurt carders complaining "zomg it nuh work" or newbs labeling it malware.  Frankly, I personaly would, but the malware label could sting abit sadly. :/
