### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by q3y** [v3n0m-Scanner/V3n0M-Scanner#139]
So I installed I'm on the step `python3 setup.py install --user`
I ran it and it gave me 
`Building from C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
url/url.cpp:4:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
I don't understand what I did wrong. Please help.
Linux version: Ubuntu 16.04.3 LTS (GNU/Linux 4.13.0-1011-azure x86_64)

**Comment by NovaCygni** [comment]
sudo apt-get install python3-dev
