### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by ansarkamina** [v3n0m-Scanner/V3n0M-Scanner#141]
python3 setup.py install --user
[sudo] password for ayan: 
No module named 'setuptools'

**Comment by ansarkamina** [comment]
└──╼ $sudo python3 setup.py install --user
[sudo] password for ayan: 
No module named 'setuptools'

**Comment by NovaCygni** [comment]
Please setup your python install properly before opening "Bug reports".... Will assume another Kali user.... another prime example while its trash...
