### ISSUE TITLE
PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----|   

### ISSUE THREAD

**Issue by JohnGott1** [v3n0m-Scanner/V3n0M-Scanner#142]
Security
------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: No module named 'aiohttp'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:

**Comment by NovaCygni** [comment]
Run `pip3 install aiohttp --upgrade --user`
forgot to add it to either recovery options my bad.

**Comment by NovaCygni** [comment]
Scratch that, Line 75 "        call("pip3 install aiohttp --upgrade --user ", shell=True)"
So in your case, it wouldve been option 2....
