### ISSUE TITLE
Problem scan URL

### ISSUE THREAD

**Issue by Mathluscan** [v3n0m-Scanner/V3n0M-Scanner#152]
After the scan of the dorks i have this : 

----------------------------------------------------------------
 Release Date Dec 25th 2018            Author: NovaCygni
        Proxy Enabled  [ False ]
        Cache & Log Status  [ Logs Cache is Empty  ]
 Please check the Misc Options for Donations Options, Thankyou
 Donating helps keep this project alive and active.
                    _____       _____
                   |____ |     |  _  |
             __   __   / /_ __ | |/' |_ __ ___
             \ \ / /   \ \ '_ \|  /| | '_ ` _ \
              \ V /.___/ / | | \ |_/ / | | | | |
    Official   \_/ \____/|_| |_|\___/|_| |_| |_| Release 425
  Harvested And Confirmed Vuln URLs in Database: [ 0 ]
  Confirmed LFI Vulns In Database: [ 0 ]
----------------------------------------------------------------

 | Domain: <> Has been targeted
 | Collected urls: 198 Since start of scan
 | D0rks: 5/5 Progressed so far
 | Percent Done: 100
 | Current page no.: <25> in Cycles of 25 Pages of results pulled in Asyncio
 | Dork In Progress: gallery.php?pre
 | Elapsed Time: 0:0:8

[+] URLS (unsorted) : Contains all the trash results still including duplicates:  198
[+] URLS (sorted)  : Trash, Duplicates, Dead-Links and other rubbish removed  14
Traceback (most recent call last):
  File "v3n0m.py", line 1307, in <module>
    fmenu()
  File "v3n0m.py", line 1059, in fmenu
    fscan()
  File "v3n0m.py", line 788, in fscan
    vulnscan()
  File "v3n0m.py", line 832, in vulnscan
    lfi_log_file = open("v3n0m-lfi.txt", "a", encoding='utf-8')
PermissionError: [Errno 13] Permission denied: 'v3n0m-lfi.txt'

What can i do ?

**Comment by Mathluscan** [comment]
I use Kali linux on windows

**Comment by kattstof** [comment]
Make sure you're running as root
