### ISSUE TITLE
I'm running ParrotSec as my OS and while installing your script, after I entered the "make" command af

### ISSUE THREAD

**Issue by WolfDaddy** [v3n0m-Scanner/V3n0M-Scanner#154]
I'm running ParrotSec as my OS and while installing your script, after wget downloaded python 3.6.3,  and tar extracted archive I entered the make command as per your instructions and it froze after this item on the print-out. 

context.load_cert_chain(CERTFILE)
ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3337)

**Comment by kattstof** [comment]
Sounds like an error in your setup.
