### ISSUE TITLE
[QUERY] change encoding

### ISSUE THREAD

**Issue by d4op** [v3n0m-Scanner/V3n0M-Scanner#155]
change on top from latin-1 to UTF-8.
and maybe encode your stuff @ line 1001/1002 in utf-8
.encode('utf-8')

the tools crashes again if i ran the code as it is on git right now with dorks all.

i am not on pc otherwise i would create commitment.

**Comment by kattstof** [comment]
sadly couldn't recreate any crashing 
nevertheless changed encoding.
