### ISSUE TITLE
Setup script exited with error: command 'x86_64-linux-gnu-gcc'

### ISSUE THREAD

**Issue by Nigrini** [v3n0m-Scanner/V3n0M-Scanner#157]
python3 setup.py install --user
running install
running bdist_egg
running egg_info
writing V3n0M.egg-info/PKG-INFO
writing dependency_links to V3n0M.egg-info/dependency_links.txt
writing requirements to V3n0M.egg-info/requires.txt
writing top-level names to V3n0M.egg-info/top_level.txt
package init file 'src/__init__.py' not found (or not a regular file)
reading manifest file 'V3n0M.egg-info/SOURCES.txt'
writing manifest file 'V3n0M.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/v3n0m
copying build/lib/v3n0m/lfisuite.py -> build/bdist.linux-x86_64/egg/v3n0m
copying build/lib/v3n0m/v3n0m.py -> build/bdist.linux-x86_64/egg/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> build/bdist.linux-x86_64/egg/v3n0m
copying build/lib/v3n0m/toxin.py -> build/bdist.linux-x86_64/egg/v3n0m
byte-compiling build/bdist.linux-x86_64/egg/v3n0m/lfisuite.py to lfisuite.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/v3n0m/v3n0m.py to v3n0m.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/v3n0m/cloudbuster.py to cloudbuster.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/v3n0m/toxin.py to toxin.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying V3n0M.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying V3n0M.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying V3n0M.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying V3n0M.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying V3n0M.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
v3n0m.__pycache__.v3n0m.cpython-37: module references __file__
creating 'dist/V3n0M-425-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing V3n0M-425-py3.7.egg
creating /root/.local/lib/python3.7/site-packages/V3n0M-425-py3.7.egg
Extracting V3n0M-425-py3.7.egg to /root/.local/lib/python3.7/site-packages
Adding V3n0M 425 to easy-install.pth file

Installed /root/.local/lib/python3.7/site-packages/V3n0M-425-py3.7.egg
Processing dependencies for V3n0M==425
Searching for url
Reading https://pypi.org/simple/url/
Downloading https://files.pythonhosted.org/packages/58/1d/492737ab1ed4ed33ce5bc00a54e92b6ad26aa793cceed097a7af389c22b3/url-0.4.2.tar.gz#sha256=8c6e4a117bfc15664319d8babca016b60dcd84c158729c1fbd309609083697b0
Best match: url 0.4.2
Processing url-0.4.2.tar.gz
Writing /tmp/easy_install-3ig5s6c8/url-0.4.2/setup.cfg
Running url-0.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3ig5s6c8/url-0.4.2/egg-dist-tmp-brz5sg3o
Building from C++
url/url.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
url/url.cpp:12497:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
url/url.cpp:12498:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
url/url.cpp:12499:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
url/url.cpp:12500:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = *type;
             ^~~~~~~~
             curexc_type
url/url.cpp:12501:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = *value;
             ^~~~~~~~~
             curexc_value
url/url.cpp:12502:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = *tb;
             ^~~~~~~~~~~~~
             curexc_traceback
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by kattstof** [comment]
yeh, the setup script can be a bit buggy. :/ sadly i won't be able to look at it until next weekend as work/Uni has me pre-occupied. just cd into the directory and python v3n0m.py or use the pkgbuild if possible.

**Comment by kattstof** [comment]
Test it now, plox.

**Comment by Nigrini** [comment]
Hi
Ok I did a git clone again and run the setup.py install --user

riaan@Xerovul:~/V3n0M-Scanner$ python3 setup.py install --user
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /home/riaan/.local/lib/python3.7/site-packages/V3n0M-425.egg-info
Writing /home/riaan/.local/lib/python3.7/site-packages/V3n0M-425.egg-info


python3 v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: [Errno 2] No such file or directory: 'lists/vuln-ftp-checklist.txt'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:1
Warning This will force upgrade all Python3.6 modules
You will have 10 seconds to cancel this action before the system begins
Note: This will entirely reinstall all current installed modules aswell to clear possible problems
Traceback (most recent call last):
  File "v3n0m.py", line 21, in <module>
    import toxin
  File "/home/riaan/V3n0M-Scanner/build/lib/v3n0m/toxin.py", line 35, in <module>
    msf_Vulns = [line.strip() for line in open("lists/vuln-ftp-checklist.txt", 'r')]
FileNotFoundError: [Errno 2] No such file or directory: 'lists/vuln-ftp-checklist.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 58, in <module>
    for dist in pip.get_installed_distributions():
AttributeError: module 'pip' has no attribute 'get_installed_distributions'


riaan@Xerovul:~/V3n0M-Scanner/build/lib/v3n0m$ python3 v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: [Errno 2] No such file or directory: 'lists/vuln-ftp-checklist.txt'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:2
This will install the missing modules and upgrade them to current versions then update your Python3.6 entirely
You will have 10 seconds to cancel this action before the system begins
Requirement already up-to-date: termcolor in /usr/lib/python3/dist-packages (1.1.0)
Requirement already up-to-date: aiohttp in /usr/local/lib/python3.7/dist-packages (3.5.4)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (1.3.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (4.5.2)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (3.0.1)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp) (18.2.0)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp) (3.0.4)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp) (2.6)
Requirement already up-to-date: asyncio in /home/riaan/.local/lib/python3.7/site-packages (3.4.3)
Requirement already up-to-date: bs4 in /usr/local/lib/python3.7/dist-packages (0.0.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4) (4.7.1)
Requirement already up-to-date: dnspython in /usr/lib/python3/dist-packages (1.16.0)
Requirement already up-to-date: tqdm in /usr/local/lib/python3.7/dist-packages (4.31.1)
Requirement already up-to-date: datetime in /home/riaan/.local/lib/python3.7/site-packages (4.3)
Requirement already satisfied, skipping upgrade: zope.interface in /home/riaan/.local/lib/python3.7/site-packages (from datetime) (4.6.0)
Requirement already satisfied, skipping upgrade: pytz in /usr/lib/python3/dist-packages (from datetime) (2018.9)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from zope.interface->datetime) (40.8.0)
Requirement already up-to-date: requests in /home/riaan/.local/lib/python3.7/site-packages (2.21.0)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.8.24)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already up-to-date: socksipy-branch in /usr/local/lib/python3.7/dist-packages (1.1)
Requirement already up-to-date: httplib2 in /home/riaan/.local/lib/python3.7/site-packages (0.12.1)
Collecting aio_ping
Installing collected packages: aio-ping
  Found existing installation: aio-ping 0.0.0
    Uninstalling aio-ping-0.0.0:
      Successfully uninstalled aio-ping-0.0.0
Successfully installed aio-ping-0.0.0
Collecting zipfile
  Could not find a version that satisfies the requirement zipfile (from versions: )
No matching distribution found for zipfile
Collecting aio-ping
Installing collected packages: aio-ping
  Found existing installation: aio-ping 0.0.0
    Uninstalling aio-ping-0.0.0:
      Successfully uninstalled aio-ping-0.0.0
Successfully installed aio-ping-0.0.0
Requirement already up-to-date: asyncio in /home/riaan/.local/lib/python3.7/site-packages (3.4.3)
Requirement already up-to-date: DateTime in /home/riaan/.local/lib/python3.7/site-packages (4.3)
Requirement already satisfied, skipping upgrade: zope.interface in /home/riaan/.local/lib/python3.7/site-packages (from DateTime) (4.6.0)
Requirement already satisfied, skipping upgrade: pytz in /usr/lib/python3/dist-packages (from DateTime) (2018.9)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from zope.interface->DateTime) (40.8.0)
Requirement already up-to-date: httplib2 in /home/riaan/.local/lib/python3.7/site-packages (0.12.1)
Requirement already up-to-date: requests in /home/riaan/.local/lib/python3.7/site-packages (2.21.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.8.24)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already up-to-date: V3n0M in /home/riaan/.local/lib/python3.7/site-packages (425)
Requirement already up-to-date: zope.interface in /home/riaan/.local/lib/python3.7/site-packages (4.6.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from zope.interface) (40.8.0)
Traceback (most recent call last):
  File "v3n0m.py", line 1182, in <module>
    d0rk = [line.strip() for line in open("lists/d0rks", 'r', encoding='utf-8')]
FileNotFoundError: [Errno 2] No such file or directory: 'lists/d0rks'

**Comment by kattstof** [comment]
You're  doing something wrong here the error is stating for some reason your d0rks file in lists folder is missing.
Download the zip manually and try it without deleting anything.

**Comment by Nigrini** [comment]
Ok - I did the following:

1. Kali Linux 2019.1 fresh install
2. Copy V3n0M-Scanner.zip file and extracted it 
3. Installed python3-dev 
4. Install python-dev
5. pip3 install aiohttp tqdm aio_ping

So up until this point all the requirements are in place (unless I am missing a part ?)

5. Execute python3 setup.py install --user  
root@Xerovul:~/V3n0M-Scanner# python3 setup.py install --user
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
creating build
creating build/lib
creating build/lib/v3n0m
copying src/v3n0m.py -> build/lib/v3n0m
copying src/lfisuite.py -> build/lib/v3n0m
copying src/cloudbuster.py -> build/lib/v3n0m
copying src/toxin.py -> build/lib/v3n0m
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
creating /root/.local/lib/python3.7/site-packages/v3n0m
copying build/lib/v3n0m/v3n0m.py -> /root/.local/lib/python3.7/site-packages/v3n0m
copying build/lib/v3n0m/lfisuite.py -> /root/.local/lib/python3.7/site-packages/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> /root/.local/lib/python3.7/site-packages/v3n0m
copying build/lib/v3n0m/toxin.py -> /root/.local/lib/python3.7/site-packages/v3n0m
byte-compiling /root/.local/lib/python3.7/site-packages/v3n0m/v3n0m.py to v3n0m.cpython-37.pyc
byte-compiling /root/.local/lib/python3.7/site-packages/v3n0m/lfisuite.py to lfisuite.cpython-37.pyc
byte-compiling /root/.local/lib/python3.7/site-packages/v3n0m/cloudbuster.py to cloudbuster.cpython-37.pyc
byte-compiling /root/.local/lib/python3.7/site-packages/v3n0m/toxin.py to toxin.cpython-37.pyc
running install_egg_info
Writing /root/.local/lib/python3.7/site-packages/V3n0M-425.egg-info

6. Execute v3n0m.py 
Exception Error Message encountered: [Errno 2] No such file or directory: 'lists/vuln-ftp-checklist.txt'

Therefore I can only assume that the missing dork file comes from your code, and not because of anything I have done ?

**Comment by kattstof** [comment]
list/vuln-ftp-checklist.txt should be in the zip directory :/ kali doesn't play nice with v3n0m

**Comment by Nigrini** [comment]
Hi kattstof

Everything up and running. Thank you.

Please let me know if / when you require someone to test your software. I will gladly assist where I can

**Comment by kattstof** [comment]
thanks , and it's not my software it's NovaCygni's I am just a contributor, but in the future if you find any bugs/error's feel free to open another support ticket. ;o
