### ISSUE TITLE
Error setup.py

### ISSUE THREAD

**Issue by Mjunior1** [v3n0m-Scanner/V3n0M-Scanner#158]
root@d00m:/pentest# git clone https://github.com/v3n0m-Scanner/V3n0M-Scanner.git
Cloning into 'V3n0M-Scanner'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1371 (delta 13), reused 0 (delta 0), pack-reused 1348
Receiving objects: 100% (1371/1371), 31.10 MiB | 20.53 MiB/s, done.
Resolving deltas: 100% (883/883), done.
root@d00m:/pentest# cd V3n0M-Scanner/
root@d00m:/pentest/V3n0M-Scanner# python3 setup.py install --user
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
creating build
creating build/lib
creating build/lib/v3n0m
copying src/lfisuite.py -> build/lib/v3n0m
copying src/v3n0m.py -> build/lib/v3n0m
copying src/toxin.py -> build/lib/v3n0m
copying src/cloudbuster.py -> build/lib/v3n0m
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
copying build/lib/v3n0m/lfisuite.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/v3n0m.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/toxin.py -> /root/.local/lib/python3.6/site-packages/v3n0m
copying build/lib/v3n0m/cloudbuster.py -> /root/.local/lib/python3.6/site-packages/v3n0m
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/lfisuite.py to lfisuite.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/v3n0m.py to v3n0m.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/toxin.py to toxin.cpython-36.pyc
byte-compiling /root/.local/lib/python3.6/site-packages/v3n0m/cloudbuster.py to cloudbuster.cpython-36.pyc
running install_egg_info
Removing /root/.local/lib/python3.6/site-packages/V3n0M-425.egg-info
Writing /root/.local/lib/python3.6/site-packages/V3n0M-425.egg-info

**Comment by Mjunior1** [comment]
OK. Done

Run commands:

`pip install aio_http`
`pip install PySocks`
`pip3 install tqdm`
`pip3 install aio_ping`

**Comment by K4bl0-Skat3R** [comment]
![2019-03-09_08-16-54](https://user-images.githubusercontent.com/7777728/54070819-d7aa1200-4243-11e9-8463-644fe3ec7a13.jpg)
error while...
running install

**Comment by Mjunior1** [comment]
> ![2019-03-09_08-16-54](https://user-images.githubusercontent.com/7777728/54070819-d7aa1200-4243-11e9-8463-644fe3ec7a13.jpg)
> error while...
> running install

Install this:

pip3 install aio_http
pip3 install PySocks
pip3 install tqdm
pip3 install aio_ping

**Comment by Diabinhodo69** [comment]
Hello friend,

1 - pip install aio_http didn't work for me. I had to pip install aiohttp
2 - On Misc options (7), using option 5 to perform forced update, we get an error of **HTTP not found**; You need to correct v3nom.py , change crimeflare.net:83 to crimeflare.net:**82**

Cheers

**Comment by ramzi410** [comment]
pip install aiohttp requires Python '>=3.4.2' but the running Python is 2.7.16
is there a why to fix this ?

**Comment by d4op** [comment]
Install 3.6 lol

**Comment by ramzi410** [comment]
root@ramzi:~/V3n0M-Scanner/src# python3 v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: No module named 'aiohttp'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:2
Traceback (most recent call last):
  File "v3n0m.py", line 5, in <module>
    import re, random, threading, socket, urllib.request, urllib.error, urllib.parse, http.cookiejar, subprocess, \
ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 44, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'
 is there a why to fix this ?

**Comment by Stainle2S** [comment]
https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/158#issuecomment-475634416

Remove python3 and python2
Install python3 first.
and use :
`pip3 install aio_http
pip3 install PySocks
pip3 install tqdm
pip3 install aio_ping`

Maybe this help for u.

**Comment by Starboy222001** [comment]
> root@:~/V3n0M-Scanner/src# python3 v3n0m.py
> 
> |------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----|
> 
> Exception Error Message encountered: No module named 'aiohttp'
> 
> |--- You are advised to run either or both steps below ---|
> |--- Recovery Menu :::: please let me know if you have any problems with it! ---|
> | --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --|
> 
> ```
>          V3n0M python modules can be updated with either option below            
> ```
> 
> [1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions,
> [2] Auto-Install all the required v3n0m modules specified in the program requirements
> [3] Exit
> 
> Note: Both recovery options will at the end, perform a check at the end so everything is upto date
> :2
> Traceback (most recent call last):
> File "v3n0m.py", line 5, in
> import re, random, threading, socket, urllib.request, urllib.error, urllib.parse, http.cookiejar, subprocess,
> ModuleNotFoundError: No module named 'aiohttp'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "v3n0m.py", line 44, in
> import pip
> ModuleNotFoundError: No module named 'pip'
> is there a why to fix this ?

any help with this?

**Comment by l4jos** [comment]
> 
> 
> > root@:~/V3n0M-Scanner/src# python3 v3n0m.py
> > |------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----|
> > Exception Error Message encountered: No module named 'aiohttp'
> > |--- You are advised to run either or both steps below ---|
> > |--- Recovery Menu :::: please let me know if you have any problems with it! ---|
> > | --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --|
> > ```
> >          V3n0M python modules can be updated with either option below            
> > ```
> > 
> > 
> > [1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions,
> > [2] Auto-Install all the required v3n0m modules specified in the program requirements
> > [3] Exit
> > Note: Both recovery options will at the end, perform a check at the end so everything is upto date
> > :2
> > Traceback (most recent call last):
> > File "v3n0m.py", line 5, in
> > import re, random, threading, socket, urllib.request, urllib.error, urllib.parse, http.cookiejar, subprocess,
> > ModuleNotFoundError: No module named 'aiohttp'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "v3n0m.py", line 44, in
> > import pip
> > ModuleNotFoundError: No module named 'pip'
> > is there a why to fix this ?
> 
> any help with this?

Yeah. You need to install all missing modules with pip3. If you can't find the module with pip3, you should check the corresponding one. Now I'm having another issue! Installing the modules replaces the default PING in the Linux distro!

`[l4jos@archlinux ~]$ ping google.nl
Traceback (most recent call last):
  File "/home/l4jos/.local/lib/python3.8/site-packages/aio_ping/__init__.py", line 587, in ping
    ping.loop.run_until_complete(ping.init(hostname))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/l4jos/.local/lib/python3.8/site-packages/aio_ping/__init__.py", line 283, in init
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW,
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
[l4jos@archlinux ~]$ sudo ping google.nl
Traceback (most recent call last):
  File "/home/l4jos/.local/bin/ping", line 36, in <module>
    from aio_ping import ping
ModuleNotFoundError: No module named 'aio_ping'
`

**Comment by TR3X-2005** [comment]
@l4jos 

> 
> Yeah. You need to install all missing modules with pip3. If you can't find the module with pip3, you should check the corresponding one. Now I'm having another issue! Installing the modules replaces the default PING in the Linux distro!
> 
> `[l4jos@archlinux ~]$ ping google.nl Traceback (most recent call last): File "/home/l4jos/.local/lib/python3.8/site-packages/aio_ping/__init__.py", line 587, in ping ping.loop.run_until_complete(ping.init(hostname)) File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/home/l4jos/.local/lib/python3.8/site-packages/aio_ping/__init__.py", line 283, in init self.socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, File "/usr/lib/python3.8/socket.py", line 231, in __init__ _socket.socket.__init__(self, family, type, proto, fileno) PermissionError: [Errno 1] Operation not permitted [l4jos@archlinux ~]$ sudo ping google.nl Traceback (most recent call last): File "/home/l4jos/.local/bin/ping", line 36, in <module> from aio_ping import ping ModuleNotFoundError: No module named 'aio_ping' `

Try this:

1. Goto https://pypi.org/project/aio_ping/#files and download the files.
2. Extract and move into the directory.
3. python3 setup.py

That should install aio_ping

Hope this helps 💀
