### ISSUE TITLE
Anomaly output links with dork grab and scan

### ISSUE THREAD

**Issue by Stainle2S** [v3n0m-Scanner/V3n0M-Scanner#163]
Hello. So, my english is badly.
I install this scanner to my termux, and when i do get dorks with domen, scanner output me 1 links about microsoft and nothing of any. And it scan with bing only? i see source of algorythm, but i dont see any problem. Please, can you help me?
Output:
Printing valid urls: http://go.microsoft.com/fwlink/?LinkId=521839
![Screenshot_20190326-044908](https://user-images.githubusercontent.com/38560847/54971186-94f77200-4f85-11e9-834e-69d368d1953a.png)

I use linux emulator in android.

**Comment by NovaCygni** [comment]
Either yout network is redirecting your requests, your not running a large enough scan to meet the minimum requests, or theres a issue with your install.

**Comment by kattstof** [comment]
it's not an issue with the code itself , its with the way Bing gathers results.
admittedly, i should've already added a sanity check to verify the targeted domain/extension is in the URL. will push fix after work if time permits.

**Comment by kattstof** [comment]
should be fixed now.
