### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by houssemak** [v3n0m-Scanner/V3n0M-Scanner#165]
hey i m new to v3n0m scannner and i dont use kali and i got those errors... any help please and thnx, i used those steps to download and install it: 
apt-get install git
git clone https://github.com/v3n0m-Scanner/V3n0M-Scanner.git
apt-get install python-dev
apt-get install python3-dev
apt-get install python3-bs4
cd V3n0M-Scanner/
python3 setup.py install --user

when installing:
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /home/houssem/.local/lib/python3.6/site-packages/V3n0M-425.egg-info
Writing /home/houssem/.local/lib/python3.6/site-packages/V3n0M-425.egg-info

when running v3n0m:
|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: No module named 'aiohttp'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date
:

**Comment by SaltyHampster** [comment]
I have same problem. Please tell me if you find a fix :)

**Comment by NovaCygni** [comment]
Help screen will be updated in next version to solve this issue for people, though "pip3 install aiohttp --user"  is all you need.
