### ISSUE TITLE
I need help here.

### ISSUE THREAD

**Issue by Kraimorskiq1** [v3n0m-Scanner/V3n0M-Scanner#166]
Hello, im getting this error when i try to scan for vuln. urls 

Exception in thread Thread-727:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "v3n0m.py", line 146, in run
    classicinj(url)
  File "v3n0m.py", line 235, in classicinj
    open("sqli_confirmed", "r+", encoding='utf-8')
OSError: [Errno 24] Too many open files: 'sqli_confirmed'

Link to picture: https://imgur.com/a/xNx49ES

I have installed threading.py

**Comment by NovaCygni** [comment]
Your running Kali in a VM and havnt followed the instructions for Kali users....

**Comment by kattstof** [comment]
it's not an issue with the code itself , its with the way Bing gathers results.
admittedly, i should've already added a sanity check to verify the targeted domain/extension is in the URL. will push fix after work if time permits.
