### ISSUE TITLE
Can't use setup.py

### ISSUE THREAD

**Issue by IchUseKomplexe** [v3n0m-Scanner/V3n0M-Scanner#168]
server@vmd39172:/home/V3n0M-Scanner$ python3 setup.py install
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
byte-compiling /usr/local/lib/python3.4/dist-packages/v3n0m/toxin.py to toxin.cpython-34.pyc
  File "/usr/local/lib/python3.4/dist-packages/v3n0m/toxin.py", line 259
    async def _invoke(self, coro_callable, *args):
            ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.4/dist-packages/v3n0m/v3n0m.py to v3n0m.cpython-34.pyc
  File "/usr/local/lib/python3.4/dist-packages/v3n0m/v3n0m.py", line 947
    async def search(pages_pulled_as_one):
            ^
SyntaxError: invalid syntax

running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/V3n0M-425.egg-info
No module named 'setuptools'
server@vmd39172:/home/V3n0M-S

**Comment by Cr0vvCEH** [comment]
pip install setuptools
