### ISSUE TITLE
Installation cancels with Setup.Py

### ISSUE THREAD

**Issue by deriko14** [v3n0m-Scanner/V3n0M-Scanner#169]
root@kali:~/Desktop/V3n0M-Scanner# python3 setup.py install --user
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /root/.local/lib/python3.7/site-packages/V3n0M-425-py3.7.egg-info
Writing /root/.local/lib/python3.7/site-packages/V3n0M-425-py3.7.egg-info

It stops there :)

**Comment by Cr0vvCEH** [comment]
same

**Comment by NovaCygni** [comment]
https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/162
Shouldve read the other issues first.
