### ISSUE TITLE
Possible to run on windows?

### ISSUE THREAD

**Issue by fantasy2025** [v3n0m-Scanner/V3n0M-Scanner#171]
C:\Users\Administrator\Downloads\V3n0M-Scanner-master\src>python v3n0m.py

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----|

 Exception Error Message encountered: No module named 'fcntl'

|--- You are advised to run either or both steps below   ---|
|--- Recovery Menu :::: please let me know if you have any problems with it!   -
--|
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install py
thon3-bs4 --|

             V3n0M python modules can be updated with either option below

[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions,
[2] Auto-Install all the required v3n0m modules specified in the program require
ments
[3] Exit

 Note: Both recovery options will at the end, perform a check at the end so ever
ything is upto date
:3

==========================
==========================

I am using windows - python latest 3.7.4
please help and let me know what option do I have beside using Linux - I want to use it on Windows. I have installed all other modules already.

I know this fcntl is only available on Linux system. However, I'd like to know if it's possible to make it work on Windows.

Thanks,

**Comment by kattstof** [comment]
Nope, some of the modules it uses don't have windows ports. 
P.S if you're still using windows you probably shouldn't be using this tool.
best regards, -KattStof

**Comment by NovaCygni** [comment]
> Nope, some of the modules it uses don't have windows ports.
> P.S if you're still using windows you probably shouldn't be using this tool.
> best regards, -KattStof

Btw dude want me to push some updates to this? Been lazy but theres a few minor fixes tweaks I can probably throw in.

**Comment by kattstof** [comment]
> 
> 
> > Nope, some of the modules it uses don't have windows ports.
> > P.S if you're still using windows you probably shouldn't be using this tool.
> > best regards, -KattStof
> 
> Btw dude want me to push some updates to this? Been lazy but theres a few minor fixes and tweaks I can probably throw in.
Sure, that'd be nice. I've been lazy aswell , branching out on making different py projects to learn more, So i haven't been giving v3n0m the attention it needs as of late.
