### ISSUE TITLE
PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by EggEngineer** [v3n0m-Scanner/V3n0M-Scanner#174]
Houston, we have a problem.

Traceback (most recent call last):
  File "v3n0m.py", line 1312, in <module>
    fmenu()
  File "v3n0m.py", line 1060, in fmenu
    fscan()
  File "v3n0m.py", line 788, in fscan
    vulnscan()
  File "v3n0m.py", line 832, in vulnscan
    lfi_log_file = open("v3n0m-lfi.txt", "a", encoding='utf-8')
PermissionError: [Errno 13] Permission denied: 'v3n0m-lfi.txt'

I'm running this as non-root user.

I have already installed dependencies and any modules it claims I am missing.

**Comment by edeyehere** [comment]
hey u can run it also with root any way i solved this problem by running the following commands
apt-get install python-dev
apt-get install python3.6-dev
apt-get install python3-bs4
pip3 install aio_http
pip3 install PySocks
pip3 install tqdm
pip3 install aio_ping



if pip3 install aio_http not working try 
sudo pip3 install aiohttp==3.0.0
sudo pip3 install --upgrade aiohttp

**Comment by SiNaPsEr0x** [comment]
> hey u can run it also with root any way i solved this problem by running the following commands
> apt-get install python-dev
> apt-get install python3.6-dev
> apt-get install python3-bs4
> pip3 install aio_http
> pip3 install PySocks
> pip3 install tqdm
> pip3 install aio_ping
> 
> if pip3 install aio_http not working try
> sudo pip3 install aiohttp==3.0.0
> sudo pip3 install --upgrade aiohttp

this solution work for fix kali linux depend of pip3.. thanks you soo much

**Comment by Jevil36239** [comment]
nope it didn't work on andro termux

**Comment by ciara1234** [comment]
Thanks for tips - PyCharm resolved a lot of packages for me and I did the below in Ubuntu WSL 😊
sudo pip3 install --upgrade aiohttp
pip3 install PySocks

**Comment by fyxtro** [comment]
I've done this all on WSL ubuntu 18.04 in win10.
I still get the same error when it is done scanning.

`Traceback (most recent call last):
  File "v3n0m.py", line 1312, in <module>
    fmenu()
  File "v3n0m.py", line 1060, in fmenu
    fscan()
  File "v3n0m.py", line 788, in fscan
    vulnscan()
  File "v3n0m.py", line 832, in vulnscan
    lfi_log_file = open("v3n0m-lfi.txt", "a", encoding='utf-8')
PermissionError: [Errno 13] Permission denied: 'v3n0m-lfi.txt'`

**Comment by kattstof** [comment]
run is as superuser, or change permission owner of the v3n0m folder
