### ISSUE TITLE
After Running V3n0M-Scanner and using the update python modules , its broken my ping on manjaro linux 5.4.18-1-MANJARO

### ISSUE THREAD

**Issue by p4yl0ad** [v3n0m-Scanner/V3n0M-Scanner#176]
Traceback (most recent call last):
 File "/home/p4yl0ad/.local/bin/ping", line 36, in <module>
    from aio_ping import ping
ModuleNotFoundError: No module named 'aio_ping'

**Comment by kattstof** [comment]
re-install aio_ping
