### ISSUE TITLE
URL (Unsorted) = a BUNCH of url but . URL (Sorted) = 0

### ISSUE THREAD

**Issue by fernandomario93** [v3n0m-Scanner/V3n0M-Scanner#177]
happens to me every time, im running good dorks, threath 100 and, search engine page 25

https://imgur.com/7UEbUz7.png

**Comment by kattstof** [comment]
don't use or you should be able to use "," to separate domain extensions.

**Comment by kattstof** [comment]
added print unsorted in latest update

**Comment by kattstof** [comment]
also, will add check for any in site array in url
as is right now it only checks if site in url
which could cause issues with someone targeting multiple domains 
p.s
Until i fix it you can edit the line that says 
`if  "="` in url and site in url:
to
`if "=" in url:`
and then just separate the domains with a comma
ex: .com, .net, .edu
