### ISSUE TITLE
How to save unsorted urls

### ISSUE THREAD

**Issue by KarimCool** [v3n0m-Scanner/V3n0M-Scanner#178]
can't seem to find a way to save the unsorted url, the file in which they should be is empty and there isn't any option for it so how to do it ?

**Comment by ZChrySA** [comment]
Did you find any way to save urls? I am facing same issue

**Comment by KarimCool** [comment]
nope sorry

**Comment by kattstof** [comment]
you can't , there's no point in saving redundant URL's , you can print them and copy pasta them if you want.

**Comment by kattstof** [comment]
added print unsorted in latest update
