### ISSUE TITLE
V3n0M scanning weird urls

### ISSUE THREAD

**Issue by CozyNeko** [v3n0m-Scanner/V3n0M-Scanner#182]
When i start to scan with v3n0m, i only get these urls:

http://help.bing.microsoft.com/#apex/18/DE/10013/-1/DE

or those

http://go.microsoft.com/fwlink/?LinkId=521839

and sometimes both

pls help, LG Cozy

**Comment by CozyNeko** [comment]
I dont know what happens, i already saw that issue somewhere in the issues but its still not working for me

**Comment by CozyNeko** [comment]
also if i put any of your given dorks to bing, it wont give me any results

**Comment by dQJVjgW2M** [comment]
> also, if I put any of your given dorks to bing, it won't give me any results

I'm having the same issue. If I scan 25 pages per dork, apparently I only get 2 URLs for each dork, even though the dorks are good.

**Comment by kattstof** [comment]
what domains are you scanning? v3n0m doesn't allow you to scan certain high level domains due to security reasons ;o

**Comment by kattstof** [comment]
Also:
Bing has checks in place that v3n0m bypasses so you wont get any results from bing.com website until a few after running v3n0m
All dorks are good and valid 
The lack of results is because you tried to scan something you shouldn't have.

**Comment by CozyNeko** [comment]
i did not specify which domain v3n0m should scan

what are the domains i cant scan tho?

**Comment by CozyNeko** [comment]
"until a few after running v3n0m"

what does that mean?

**Comment by CozyNeko** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/72229088/101391799-237c6600-38c5-11eb-9bfd-651da8020f80.jpg)

**Comment by kattstof** [comment]
Don't use * just use .com the use for * to force domain was fixed over a year ago.
As for "what does that mean" it means what i said.

**Comment by CozyNeko** [comment]
i already did only .com, is not working either way

**Comment by kattstof** [comment]
Note: Just for giggles, i used current git source on a fresh install of Arch, and it's working flawlessly OP is just having user error and/or didn't RTFM

**Comment by kattstof** [comment]
just pushed an update, let me know if it fixed this.
