### ISSUE TITLE
V3n0m scanning only a few strange urls.

### ISSUE THREAD

**Issue by Kolufs** [v3n0m-Scanner/V3n0M-Scanner#184]
For some reason, v3n0m only scans the following urls:

- http://go.microsoft.com/fwlink/?LinkId=521839
- https://privacy.microsoft.com/pt-br/privacystatement

I tested on CentOs, Arch, and Kali, all appear to have the same result, i'am installing as instructed on the github page, also tried different dorks to no avail.

**Comment by kattstof** [comment]
What domains are you scanning?

**Comment by Kolufs** [comment]
.com

**Comment by Kolufs** [comment]
> What domains are you scanning?

.com

**Comment by kattstof** [comment]
Yea it seems bing is trying to block dorking because site: ends up throwing that aswell as .com but com (without the dot) will give me results, gimme a few to try to work on a fix.

**Comment by kattstof** [comment]
just pushed an update, let me know if it fixed this.

**Comment by Kolufs** [comment]
It didn't work, even without the dot.

> just pushed an update, let me know if it fixed this.

**Comment by kattstof** [comment]
You sure you tried the new update? Because it fixed it for me.

**Comment by Kolufs** [comment]
Yes, same thing.

**Comment by kattstof** [comment]
Try enabling tor in v3n0m, or use a vpn bing might be blocking your ip.

**Comment by Kolufs** [comment]
I enabled, same thing.

**Comment by kattstof** [comment]
try a fresh install with the newest update? the update i pushed last night seems to have fixed it for me and a few other people, but not for you oddly.

**Comment by Kolufs** [comment]
Tried it on a fresh install of kali, same thing, is there some info that i could share to help you pinpoint the error ?

**Comment by kattstof** [comment]
Okay
When it says domain put .com
Dorks 10
Threads 100
Pages 25 
When its done hit the print UNSORTED URLS option and copy paste the result here plox

**Comment by Kolufs** [comment]
> Okay
> When it says domain put .com
> Dorks 10
> Threads 100
> Pages 25
> When its done hit the print UNSORTED URLS option and copy paste the result here plox

http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
http://go.microsoft.com/fwlink/?LinkId=521839
https://www.bing.com/aclick?ld=e8q0NSYW_PMqdGe2j8ZBoufDVUCUxv2toEOOQ1fnfL2htGJAX--t67y97w-xsfLLfnB_gb4FvfdPaxCWPZathDjtEuQQBoWZWDqLRuSRZLLZvCrGdnZk3bALf4YEdk9prrrmRiaHzjdNMAnzB9ozjaPwAAvUkqtHpFokysrrcoQsvyNqqu&amp;u=aHR0cCUzYSUyZiUyZnd3dy5ib29raW5nLmNvbSUyZmhvdGVsJTJmcnMlMmZhZHJlc2EuaHRtbCUzZmFpZCUzZDM2MzE4MyUyNmxhYmVsJTNkbXNuLUN3YkF4RE9Yeipoc2lCbkYqMEZ1UUEtODA4ODI5MjYzNzY1OTglM2F0aWt3ZC0xMzgxMjY2OTI3MzklM2Fsb2MtMTcwJTNhbmVvJTNhbXRwJTNhZGVjJTNhcXMqaW5jKi5waHAlMjUzRmFkcmVzYSUyNTNEJTI1MjBzaXRlJTI1M0EuY29tJTI2dXRtX2NhbXBhaWduJTNkSG90ZWwlMjUyMC0lMjUyMFNlcmJpYSUyNnV0bV9tZWRpdW0lM2RjcGMlMjZ1dG1fc291cmNlJTNkYmluZyUyNnV0bV90ZXJtJTNkQ3diQXhET1h6KmhzaUJuRiowRnVRQSUyNm1zY2xraWQlM2RjYzA1MzY1MzI1NmYxYmQ3NGEzNzY5YTZlYzIyZDAxYQ&amp;rlid=cc053653256f1bd74a3769a6ec22d01a

**Comment by kattstof** [comment]
Sadly there's not much i can do atm  , can't find why it's working for me (even made a fresh install of arch and redownloaded the repo, and the new patch  is working for me) I'll leave this 
open until i can find a fix or work around. Sorry mate.

**Comment by mbollini72** [comment]
Hi kattstof, same problem here :( I'm using the latest version. Unsorted urls are the same reported by user Kolufs.

**Comment by kattstof** [comment]
give me a few days to find a decent search engine to change to since bing is turning to arse.

**Comment by kattstof** [comment]
Try it now

**Comment by mbollini72** [comment]
Really strange kattstof, same problem as before.
After scanning the application it's showing me just these 2 urls, repeated:
http://go.microsoft.com/fwlink/?LinkId=521839
http://help.bing.microsoft.com/#apex/18/IT/10013/-1/IT

**Comment by kattstof** [comment]
Yea, bing keeps blocking. I switch browser headers with requests and itll work for a while then block again.
