### ISSUE TITLE
package init file 'src\__init__.py' not found (or not a regular file)

### ISSUE THREAD

**Issue by NamOtaku** [v3n0m-Scanner/V3n0M-Scanner#186]
C:\Users\Administrator\Desktop\V3n0M-Scanner-master>setup.py build
running build
running build_py
package init file 'src\__init__.py' not found (or not a regular file)
package init file 'src\__init__.py' not found (or not a regular file)

**Comment by kattstof** [comment]
you're using windows. this doesn't work on windows.
