### ISSUE TITLE
Current status Update

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#187]
Due to unforeseen circumstances i haven't had much time to update this. However with Nova afk for a year now i don't want to leave the project dark.
yes, v3n0m rn is broken because bing started ip blocking, yes it's a simple fix. 
however the current planned fix from me is to grab random proxies  and use a random proxy per request.
the current issue with this fix is it is extremely slow, and i don't feel like the quality is up to par to push it in it's current state.
when i can iron out the kinks, i'll push the update. but it might be a minute as i have irl duties that  sadly take me afk for long periods of time.
if anyone has an idea on a better/faster fix feel free to comment here and let me know.

**Comment by chablitzel** [comment]
Thanks for the update. I refreshed every day, since I really love your tool and I miss it so much - really sad, that it isn't working at the moment. I am really looking forward to the update but I understand that you also have a private life ;)

**Comment by kattstof** [comment]
If you set v3n0m to use tor and set your tor conf file to change ip every 10 seconds , it should be a nice work around. However I don't want to force tor use at main either because i want it to remain plug and play with tor as an option

**Comment by chablitzel** [comment]
It works! I edited **/etc/torc/torrc** and added these lines:

**CircuitBuildTimeout 10
LearnCircuitBuildTimeout 0
MaxCircuitDirtiness 10**

After starting the tor service, I selected the proxy in the main menu of v3n0m and configured it to use no auth, socks5, 127.0.0.1 : 9050 to use the tor as the proxy.

You get a new IP every 10 seconds and can avoid the IP ban for the most part.

**Comment by kattstof** [comment]
also notes for anyone in need while im afk
 if you have the time you can edit  the src to make tor change ip every request. (ignoringget is the line for requests) should make it work as good as before.
if you host searx yourself you can also change bing to searx and get better results.
you can also have python use proxy websites  to grab a random proxy + change proxy with every request. not too hard just make a function getproxy and pass proxy ie request(url, headers=proxy)
i'm currently testing to see which approach works best.

**Comment by kattstof** [comment]
@chablitzel  i just pushed an update that should make tor work loads better, would you mind testing the update?

**Comment by chablitzel** [comment]
Will test it today!

**Comment by chablitzel** [comment]
> @chablitzel i just pushed an update that should make tor work loads better, would you mind testing the update?

Sorry for just getting back to you - I completely forgot to reply. I am testing it at the moment and it looks like it works perfectly again! 

Before I was getting blocked after 5-10 requests and now it already collected thousands of valid URLs again. After the scan is finished, I will look, how many junks results are included due to Bing blacklisting my IP.

I setup Tor with the MaxCircuitDirtiness 10 and used it like described in my post above (as Proxy in v3n0m).

Thank you very much for your work and continued effort in maintaining this!

**Comment by D3m0ni4k** [comment]
I tried it now it work
