### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mehranexpert** [v3n0m-Scanner/V3n0M-Scanner#19]
root@kali:/usr/local/lib/python2.7/dist-packages/v3n0m# python3 v3n0m.py
  File "v3n0m.py", line 57
    print " please make sure you have all of the following modules: re, random, threading, socket, urllib2, cookielib, subprocess, codecs, signal, time, sys, os, math, itertools"
                                                                                                                                                                                 ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by NovaCygni** [comment]
install python3, your trying to run it in Python2 thats why your error message contains the address for your python 2.7 install.

**Comment by c0deh4xor** [comment]
I actually just got this same error with kali 2.0-rolling (2016.1)...
root@sdksdk:/usr/local/lib/python3.5/dist-packages/v3n0m# python3 v3n0m.py
  File "v3n0m.py", line 57
    print " please make sure you have all of the following modules: re, random, threading, socket, urllib2, cookielib, subprocess, codecs, signal, time, sys, os, math, itertools"
                                                                                                                                                                                 ^
SyntaxError: Missing parentheses in call to 'print'

I re-ran it with 
python v3n0m.py
and it runs fine... python --version shows 2.7.11

**Comment by NovaCygni** [comment]
You are running an old outdated version of V3n0M. the Latest  version is 4.0.2c...
--> SyntaxError: Missing parentheses in call to 'print' <-- is using 'print' not ("Print") which indicates the V3n0M is not the Python3 version.
