### ISSUE TITLE
Need help installing v3n0m-scanner

### ISSUE THREAD

**Issue by maware1912** [v3n0m-Scanner/V3n0M-Scanner#190]
Hey guys I tried a lot of things really but nothing seems to be working can anyone give step by step guide which is up to date,
on how to install v3n0m-scanner? I will really appreciate you help, big thanks in advance.

**Comment by maware1912** [comment]
![venom](https://user-images.githubusercontent.com/85826943/122210498-62abf500-ceae-11eb-8ce9-b375fe36cf0b.PNG)

**Comment by D3m0ni4k** [comment]
Type 2 to install modules missing

**Comment by d4op** [comment]
if this won't work try to install the missing modules  manually. 
look at the file and look which modules get imported install them via pip (pip3)

but as I see it tells httplib2 is missing so simply try to fix it typing pip3 install httplib2 or pip install httplib2

**Comment by kattstof** [comment]
Odd, went and rechecked to make sure httplib is being installed via the error detection and pip3 install httplib2 is being called properly
Perhaps ops system requires pip install?

**Comment by D3m0ni4k** [comment]
> Odd, went and rechecked to make sure httplib is being installed via the error detection and pip3 install httplib2 is being called properly
> Perhaps ops system requires pip install?

Try sudo apt-get install -y python-httplib2

**Comment by D3m0ni4k** [comment]
> if this won't work try to install the missing modules manually.
> look at the file and look which modules get imported install them via pip (pip3)
> 
> but as I see it tells httplib2 is missing so simply try to fix it typing pip3 install httplib2 or pip install httplib2

Try sudo apt-get install -y python-httplib2
If that don't work try this
sudo apt update
sudo apt install python2 ca-certificates python3-httplib2
cd ~
wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-httplib2/python-httplib2_0.14.0-1ubuntu1_all.deb
sudo apt install ./python-httplib2_0.14.0-1ubuntu1_all.deb

**Comment by vittring** [comment]
@maware1912 / Have you solved this issue by using any of the above solutions? If you have, this issue can be pinned and closed. If you still have issues installing, try using Docker (there's an optional install video for it, and everything will be done for you); or reinstalling your Python and using version 3 of pip to install (pip install --user httplib2).

@D3m0ni4k / `Try sudo apt-get install -y python-httplib2` is not necessary if you're not regularly updating your python modules, e.g. every day or two. It's up to you to decide which, but using both can break some installations. Some package managers "customize" things and it can break packages. It's safer to use Pip.

Docker is probably the easiest, followed by manually installing pip and the missing modules from source.

**Comment by D3m0ni4k** [comment]
> @maware1912 / Have you solved this issue by using any of the above solutions? If you have, this issue can be pinned and closed. If you still have issues installing, try using Docker (there's an optional install video for it, and everything will be done for you); or reinstalling your Python and using version 3 of pip to install (pip install --user httplib2).
> 
> @D3m0ni4k / `Try sudo apt-get install -y python-httplib2` is not necessary if you're not regularly updating your python modules, e.g. every day or two. It's up to you to decide which, but using both can break some installations. Some package managers "customize" things and it can break packages. It's safer to use Pip.
> 
> Docker is probably the easiest, followed by manually installing pip and the missing modules from source.

I have fix it with my method 😉

**Comment by ashok784** [comment]
Please tell me how i can run 3 command, when i copy and paste i got this error
![WhatsApp Image 2021-07-28 at 1 03 05 PM](https://user-images.githubusercontent.com/88039429/127282761-ee726434-5725-44d6-86a2-95c53fe7d9be.jpeg)
