### ISSUE TITLE
stucking at sqli test

### ISSUE THREAD

**Issue by d4op** [v3n0m-Scanner/V3n0M-Scanner#193]
noticed that the whole program freezes or stops while processing the sqli testing.
I think it audited 120 urls and now nothing happens.

someone already looked into this ?

**Comment by vittring** [comment]
Please paste the output of the logs from venom or any other indicators.

**Comment by d4op** [comment]
There are no indicators, the output are the urls which are vulnerable to sqli. 
but it simple stops and freeze after a while.
it only happens if I did before a whole dork search with all dorks.

**Comment by kattstof** [comment]
Any specific way to recreate this issue? just ran a quick scan and its working for me. were you using all dorks? if not how many and what target domain.

**Comment by d4op** [comment]
used all dorks for country at

**Comment by vittring** [comment]
This is user-specific and can't be recreated. Have you gotten the program to work on a different system? A virtual machine or Docker perhaps? The default image just installs the necessary plugins and works fine on any system that supports virtualization. I can't find any issue. Try to provide more information such as screenshots that can be any more helpful.
