### ISSUE TITLE
v3n0m installing issue

### ISSUE THREAD

**Issue by ashok784** [v3n0m-Scanner/V3n0M-Scanner#194]
┌──(root💀kali)-[~]
└─# cd V3n0M-Scanner/src/
                                                                                                                                                                       
┌──(root💀kali)-[~/V3n0M-Scanner/src]
└─# python3 ./v3n0m.py             

|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
 
 
 Exception Error Message encountered: No module named 'aio_ping'
 
 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu :::: please let me know if you have any problems with it!   ---| 
| --Note, if your running Ubuntu you may need to run --> sudo apt-get install python3-bs4 --| 
 
             V3n0M python modules can be updated with either option below            
[1] Run Pip3.6 and Auto-Update Python3.6 modules to latest versions, 
[2] Auto-Install all the required v3n0m modules specified in the program requirements
[3] Exit
 
 
 Note: Both recovery options will at the end, perform a check at the end so everything is upto date

**Comment by vittring** [comment]
Have you tried running it in virtualenv?

**Comment by ashok784** [comment]
> Have you tried running it in virtualenv?

Yes I am trying in virtual linux

**Comment by vittring** [comment]
Please create a virtualenv using python and upgrade pip. `virtualenv3.8 .` | ` source bin/activate`.
Then call `python` and install each one manually to resolve conflicts in python.

**Comment by vittring** [comment]
Also, somewhat related but may not solve your dependencies issue, see above Pull Request for information on necessary modules.

**Comment by vittring** [comment]
This issue can be closed.
