### ISSUE TITLE
SQLi Testing function does not work

### ISSUE THREAD

**Issue by qazxcv1234QWER** [v3n0m-Scanner/V3n0M-Scanner#206]
Hi, installed all the notes. The program starts and finds vulnerable links. The SQLi Testing function does not work
I write number 1.
the program resets and returns to the original screen
![4241](https://user-images.githubusercontent.com/90816934/133549391-1fb1e196-91e5-4041-ac20-bb8d87669d6a.png)
![1](https://user-images.githubusercontent.com/90816934/133549410-994191d0-82ff-49c8-940d-19edde44f0ef.png)
![23](https://user-images.githubusercontent.com/90816934/133549416-e703394b-ca94-4ce3-ae30-ac90069e460a.png)

**Comment by kattstof** [comment]
it works, it just didn't find any vulns in the scan you ran.
when sorted it shows there were only 7 valid url's to scan and none of those 7 were vulnerable to SQLI

**Comment by qazxcv1234QWER** [comment]
hello it doesn't work
Finds links but doesn't scan them for SQl.
outputs 0 at once


пт, 17 сент. 2021 г., 13:15 Katt Stof ***@***.***>:

**Comment by kattstof** [comment]
it works i just tested it on a fresh install, you're using it wrong. if it says it didnt find anything vulnerable it didn't find anything vulnerable. this is user error not a problem with venom. like i said it only scanned 7 url's hence why it didnt find a vuln. run a bigger scan.

**Comment by qazxcv1234QWER** [comment]
I scanned many times. It does not find SQl vulnerabilities


сб, 18 сент. 2021 г., 05:33 Katt Stof ***@***.***>:

**Comment by qazxcv1234QWER** [comment]
Xss testing.no job

пт, 17 сент. 2021 г., 13:15 Katt Stof ***@***.***>:

**Comment by qazxcv1234QWER** [comment]
Неllo

do I need to use my dorks to find SQL?


пт, 17 сент. 2021 г., 13:15 Katt Stof ***@***.***>:

**Comment by d4op** [comment]
it has build in d0rk list if you wish to use your own feel free.
little hint if you use a vpn switch the server or maybe use tor feature.
maybe the SE used for dorking is blocking your ip and you get bad results for sql testing :)
