### ISSUE TITLE
Proxy not working?? 

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#209]
Might be a bug on my end but it seems when proxy is enabled it isn't actually going through the proxy, when using the proxy_enabled code in its own script it goes through just fine so the code is valid, but if ran through v3n0m itself it doesn't. will do a fresh install tonight to see if it's a environment issue.

**Comment by vittring** [comment]
You're using Tor as the proxy, yes?

**Comment by kattstof** [comment]
Yessir , and its not a enviroment issue as far as i can tell because i tested it on a fresh vm just to be sure. From what i gathered It seems its a bug in socksipy being not compatible with asyncio but instead of throwing an exception is just ignores it and continues without using a proxy . And setting proxy requests to use socks5 manually just throws an error due to incompatibility with asyncio/threading.

**Comment by vittring** [comment]
Okay, it looks like it's specifically socksipy that is broken.

**Comment by vittring** [comment]
I've isolated it to within socksipy as you've suggested was the issue. Unfortunately, I can't diagnose it either.

**Comment by kattstof** [comment]
Luckily the updated list of ~3000 headers seems to work (for now) to negate the necessity for tor, in my limited testing, i'll keep this open until I/someone else can figure out the issue

**Comment by vittring** [comment]
I was thinking the same. Maybe time to stop requiring Tor? 

I've also fixed a dependency issue leading to a HTTP injection vulnerability in #210. 

aiohttp 3.7.4.post0 -> 3.8.0.post0

On Jan 5, 2022, 10:23 PM, at 10:23 PM, Katt Stof ***@***.***> wrote:
>Luckily the updated list of ~3000 headers seems to work (for now) to
>negate the necessity for tor, in my limited testing, i'll keep this
>open until I/someone else can figure out the issue
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/209#issuecomment-1006254927
>You are receiving this because you commented.
>
>Message ID:
***@***.***>

**Comment by kattstof** [comment]
Merged
 also removed note about tor requirement and replaced with a statement to use proxies/vpn because without doing so they (end users) will get flagged by akamai which wont affect them being able to use venom but would make said ip blacklisted from alot of websites (including psn/nvidia) until akamai decides the ip is no longer dirty (which could take from a few days to a few months)

**Comment by vittring** [comment]
Confirmed. If anybody has any questions about why we don't automatically integrate Tor this is why. Unforeseen circumstances that we can't resolve one way will be resolved in another. 

This doesn't change the effectiveness of the program. It only changes how you need to _think_ about when using it. 

Has anybody else - including the ones who have forked this project, besides myself and @kattstof - been able to torify this in a roundabout way? 

I always believed it was pretty archaic to force one way of thinking.

**Comment by kattstof** [comment]
Well i must say i feel stupid. The reason the proxy doesn't work is because the implementation of f_menu().
 every time you call f_menu() it will re-write proxy_enabled to False. if i set proxy to enabled before ever calling f_menu i can get it to work BUT it would have to be before the logo and main menu meaning the first thing a user will see would be "Do you want to use a proxy y/n " which IMO looks ugly. using a menu option for enabling it using a global scope also doesn't seem to work for some reason.
 the code for getting it to work(after first prompting the user with a y/n prompt):
 `
if proxy == False:
    def ignoring_get(url):
            header = [line.strip() for line in open("lists/header", "r", encoding="utf-8")]
            ua = random.choice(header)
            headers = {"user-agent": ua}
            try:
                try:
                    response = requests.get(url, headers=headers, timeout=2)
                    response.raise_for_status()
                except Exception:
                    return ""
                return response.text
            except Exception as verb:
                print(str(verb))
if proxy == True:
    def  ignoring_get(url):
        proxies = {'http': 'socks5h://127.0.0.1:9050', 'https': 'socks5h://127.0.0.1:9050'}
        header = [line.strip() for line in open("lists/header", "r", encoding="utf-8")]
        ua = random.choice(header)
        headers = {"user-agent": ua}
        try:
            try:
                response = requests.get(url, headers=headers,proxies=proxies, timeout=2)
                response.raise_for_status()
            except Exception:
                return ""
            return response.text
        except Exception as verb:
            print(str(verb))
`
