### ISSUE TITLE
Docker: No module named 'dns'

### ISSUE THREAD

**Issue by abnerrizzi** [v3n0m-Scanner/V3n0M-Scanner#229]
On my very frst time trying to run this tool under docker I used the commands below:

`$ docker run --rm -ti vittring/venom:devel`

After start the containner I entered:

> - 4
> - google.com
> - 2

then I got the error below:

```
Traceback (most recent call last):
  File "/opt/scan/src/modules/dnsbrute.py", line 18, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'
```

**Comment by kattstof** [comment]
should be fixed  now , i made a pull request for @vittring's fork so i await his merge

**Comment by vittring** [comment]
Merged your changes. I also pushed a new tag: 'Yggdrasil' + 'devel' that both fix other issues within the container.
