### ISSUE TITLE
injectionthread

### ISSUE THREAD

**Issue by d4op** [v3n0m-Scanner/V3n0M-Scanner#26]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "v3n0m.py", line 133, in run
    classicinj(url)
  File "v3n0m.py", line 147, in classicinj
    resp = urllib.request.urlopen(aug_url)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 375, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.4/http/client.py", line 266, in parse_headers
    raise HTTPException("got more than %d headers" % _MAXHEADERS)
http.client.HTTPException: got more than 100 headers

after some time getting this on 11.000s urls

**Comment by NovaCygni** [comment]
Ill try and reproduce it in Pycharm so I can check whats being sent/recieved, really I shouldve added a option to import a txt file of urls to run checks against, ie for debugging like in this case.

**Comment by d4op** [comment]
its not the problem of your code, i guess the problem is a misconfigured server which gets checked.
maybe it produces more thatn 100 headers like set-cookie or such stuff.
will hotpatch the http client for more headers like 100000

**Comment by d4op** [comment]
PS: add a function where it asks: Start SQLi or Main Menu -> Save sorted URLS to txt file.
and at startup in menu add a point where u can load custom txt files for sqli checks

**Comment by NovaCygni** [comment]
you mean like https://bugs.python.org/issue16037 or https://bugs.python.org/issue22928 style bugs? yeh its likely Python itself by just as likely as a result of something I havnt prepared for in advance. Well im working on a TKinter for whats currently the FTP crawler, no reason It should be limited to FTP scans, will probably throw in a bunch of other port banner checks for the other ports, put in a simple GeoIP and map and work from there.

**Comment by d4op** [comment]
BTW you need to change your required packages print:
you need to pip3 install requests and urllib2 too !

**Comment by d4op** [comment]
for other people with max header problems or dork encoding:
hotpatch: /usr/lib/python3.4/http/client.py with nano
MAX HTTP HEADER 100 to 100000
and asci encoding to utf-8

**Comment by NovaCygni** [comment]
Requests is already listed in the setup.py along with what else is needed (* and did you mean httplib2 not urllib2? *)...
Im going to gather not everyones installing via Blackarch and people are just downloading the github :/

**Comment by d4op** [comment]
jeah httplib2

**Comment by d4op** [comment]
there is a bug, if the urls are sorted and it starts the injection thread, there are still duplicates, like
www.xxx.com
xxx.com
thats because you dont remove the www before sorting.
strip www. away before sorting to prevent dups.

**Comment by NovaCygni** [comment]
"Shouldnt" happen anymore in Asyncio, have added the www. stripper in and will upload new version tonight/tomorrow-morning.
