### ISSUE TITLE
Gui Layout

### ISSUE THREAD

**Issue by NovaCygni** [v3n0m-Scanner/V3n0M-Scanner#27]
Partially built GUI frame for the scanner, now just importing code one piece at a time.
http://postimg.org/image/c1bzg137f/

**Comment by d4op** [comment]
Nice GUI, but put it as optinal, like a arg, --gui so the v3n0m scanner can still be run on linux boxen (ssh vps/dedicated)

**Comment by NovaCygni** [comment]
That's actually what I was doing with the parse options, when I've got all the current code working with the GUI I can work on the other issues.

**Comment by NovaCygni** [comment]
Scrapped for the moment... will leave the dead branch in existence though if anyone wants to take it.
