### ISSUE TITLE
image speaks for itself

### ISSUE THREAD

**Issue by Asexual** [v3n0m-Scanner/V3n0M-Scanner#28]
http://i.imgur.com/568Lyq0.png

**Comment by NovaCygni** [comment]
I fail to see what the issue is, aside from the non-implemented imports not really being required at the moment/anymore your picture says nothing... So what's this supposed issue that 'speaks for itself'?

**Comment by NovaCygni** [comment]
.... Closed the issue as a non-value, non-input post... Updated the error message to make it easier for "Special" people to understand. Added rest of imports to the "Setup.py".....
