### ISSUE TITLE
Installing V3n0M

### ISSUE THREAD

**Issue by MichaelPavlov** [v3n0m-Scanner/V3n0M-Scanner#30]
Hi there. I'm experiencing issue with installing, here is my output 

`Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    packages=['v3n0m'], requires=['aiohttp', 'httplib2', 'socksipy-branch', 'requests', 'dns', 'url']
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.4/distutils/dist.py", line 252, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.4/distutils/dist.py", line 1209, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.4/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-branch'`

I guess some components missing from requires list, so I made

`pip3 install aiohttp httplib2 socksipy-branch requests dns url`

I'm not very familiar with python and mb I'm doing something wrong. Please correct me.

**Comment by MichaelPavlov** [comment]
Ok, I goggled something and made a little script on python which checks my missing packages

`import pip
installed_packages = pip.get_installed_distributions()

flat_installed_packages = [package.project_name for package in installed_packages]

packages = [
	"aiohttp",
	"httplib2",
	"socksipy-branch",
	"requests",
	"dns",
	"url"
]

some_list = ['abc-123', 'def-456', 'ghi-789', 'abc-456']
bad = ['abc', 'def']
for needle in packages:
	if needle not in flat_installed_packages:
          print('Not found ', needle)
`

This gave me 

`Not found  socksipy-branch
Not found  dns
`
I tried 

`sudo -H pip3 install SocksiPy-branch
sudo -H pip3 install dnspython`

output

`Requirement already satisfied (use --upgrade to upgrade): SocksiPy-branch in /usr/local/lib/python2.7/dist-packages`

So as I can see it installing into wrong python version, despite I'm using pip3. How do I install them into python3?

**Comment by MichaelPavlov** [comment]
Guys it was incredible. I've learned python basics, wrote simple script to check imports, now I  know about package management in python, I know about issues when different versions of python installed, I've got bunch of accounts on various python forums, I finally got membership on stackoverflow and askubuntu. I have learned about virtual environment in python, I know what it's for, how to setup and use it. And after all I had nice idea. I just deleted these bloody imports from requires list in setup.py. And guess what? It works now!

**Comment by NovaCygni** [comment]
You can remove both from requirements they are standard as of 3.4 I believe.

**Comment by MichaelPavlov** [comment]
That's exactly what I did, but I got an error  in runtime
`in <module>
    import queue
ImportError: No module named queue`

**Comment by NovaCygni** [comment]
can also be removed.. alot of the imports are either outdated from various methods ive looked into and been to lazy to remove, as im working on a new GUI version along with some work on EMP-Jammers doing minor cleaning and updating on old code isnt a priority though feel free to submit and pulls you feel need doing. 
Atm im working on Asyncio and TKinter so I can Async 200 requests per second instead of the 0.80 per second it is atm, I want the speed to be realistic and non-painful.

**Comment by NovaCygni** [comment]
Btw: queue, asyncio, aiohttp arnt used in the current released version but will be being used in the next release, so are safe to remove, though you should already have these modules installed.

**Comment by kangoo13** [comment]
I removed queue, asyncio, aiohttp from the imports but still can't launch the venom.py getting the same error message
