### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jhautefeuille** [v3n0m-Scanner/V3n0M-Scanner#33]
```
bob@ricard:~/V3n0M-Scanner/srcᛤ python3 v3n0m.py
  File "v3n0m.py", line 393
    async def tcp_scanner(ip, port, loop=None):
            ^
SyntaxError: invalid syntax

```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
3.13.0-85-generic #129-Ubuntu SMP

**Comment by NovaCygni** [comment]
thats correct Syntax, code works fine, likely a issue with your Python distro (*  Have you made sure you have installed asyncio? *)

**Comment by jhautefeuille** [comment]
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> dir(asyncio)
['ALL_COMPLETED', 'AbstractChildWatcher', 'AbstractEventLoop', 'AbstractEventLoopPolicy', 'AbstractServer', 'BaseEventLoop', 'BaseProtocol', 'BaseTransport', 'BoundedSemaphore', 'CancelledError', 'Condition', 'DatagramProtocol', 'DatagramTransport', 'DefaultEventLoopPolicy', 'Event', 'FIRST_COMPLETED', 'FIRST_EXCEPTION', 'FastChildWatcher', 'Future', 'Handle', 'IncompleteReadError', 'InvalidStateError', 'JoinableQueue', 'LifoQueue', 'Lock', 'PriorityQueue', 'Protocol', 'Queue', 'QueueEmpty', 'QueueFull', 'ReadTransport', 'SafeChildWatcher', 'SelectorEventLoop', 'Semaphore', 'StreamReader', 'StreamReaderProtocol', 'StreamWriter', 'SubprocessProtocol', 'SubprocessTransport', 'Task', 'TimeoutError', 'TimerHandle', 'Transport', 'WriteTransport', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'as_completed', 'async', 'base_events', 'base_subprocess', 'constants', 'coroutine', 'coroutines', 'create_subprocess_exec', 'create_subprocess_shell', 'events', 'futures', 'gather', 'get_child_watcher', 'get_event_loop', 'get_event_loop_policy', 'iscoroutine', 'iscoroutinefunction', 'locks', 'log', 'new_event_loop', 'open_connection', 'open_unix_connection', 'protocols', 'queues', 'selector_events', 'selectors', 'set_child_watcher', 'set_event_loop', 'set_event_loop_policy', 'shield', 'sleep', 'sslproto', 'start_server', 'start_unix_server', 'streams', 'subprocess', 'sys', 'tasks', 'transports', 'unix_events', 'wait', 'wait_for', 'wrap_future']
>>> 


I'll install Python 3.5... Thank you for answer.

**Comment by NovaCygni** [comment]
Thanks for feedback its appreciated aswell :) Enjoy V3n0M, before jumping in the deep end and user the scanner at full power of all d0rks, id suggest trying something like 200, with pages at once set to 50 :D :D: :D ;) V3n0M is easily the most powerful d0rker yourll ever use.

**Comment by Al3xjohn** [comment]
# You can install python  3.6 with these commands

`wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.t`gz
`tar xvf Python-3.6.3.tgz`
`cd Python-3.6.3`
`./configure --enable-optimizations`
`make -j8`
`sudo make altinstall`
`python3.6`

It is recommended to use `make altinstall ` according to the [official website.](https://docs.python.org/3/using/unix.html#building-python)
