### ISSUE TITLE
unsorted urls

### ISSUE THREAD

**Issue by plexer40** [v3n0m-Scanner/V3n0M-Scanner#34]
i cant find how to save unsorted urls before testing sqli ?
i need unsorted urls
even sorted urls also impossible to save

**Comment by NovaCygni** [comment]
adding a option in the next build update, and changing the logfile locations, you can find you sorted list by searching for "v3n0m-sqli.txt", it generates the list in the folder v3n0ms installed to, which is what the change in next update rectifies.

**Comment by plexer40** [comment]
thank you. But will be good if also adding option for unsorted url
