### ISSUE TITLE
Im kinda new (and retarded)

### ISSUE THREAD

**Issue by AnalBeef** [v3n0m-Scanner/V3n0M-Scanner#35]
So when I try and run the v3n0m.py in src I get 

python3.5 v3n0m.py 
 please make sure you have all of the following modules: asyncio, aiohttp, codecs, requests
 httplib2, signal, itertools
Error a module was not found,  'sudo pip3 install <package name>' to install

But when I try and install the things im missing i get this 

sudo pip3 install codecs requests signal itertools
Downloading/unpacking codecs
  Could not find any downloads that satisfy the requirement codecs
Cleaning up...
No distributions at all found for codecs
Storing debug log for failure in /root/.pip/pip.log

and it happens with requests , signal , itertools and codecs all the other ones installed fine

**Comment by NovaCygni** [comment]
You should be able to remove them from the "Imports" list as are included as part of Python3.5
