### ISSUE TITLE
EROOR- 

### ISSUE THREAD

**Issue by morrisonm6** [v3n0m-Scanner/V3n0M-Scanner#36]
root@kali:/usr/src/volatility-tools/src# python v3n0m.py
  File "v3n0m.py", line 423
    def tcp_Scanner_run(tasks, *, loop=None):
                                ^
SyntaxError: invalid syntax
root@kali:/usr/src/volatility-tools/src# python3 v3n0m.py
 please make sure you have all of the following modules: asyncio, aiohttp, codecs, requests
 httplib2, signal, itertools
Error a module was not found,  'sudo pip3 install <package name>' to install
root@kali:/usr/src/volatility-tools/src# python3.5 v3n0m.py
 please make sure you have all of the following modules: asyncio, aiohttp, codecs, requests
 httplib2, signal, itertools
Error a module was not found,  'sudo pip3 install <package name>' to install
...........................................................................................................................................................
Then when i go to install those packages i get : root@kali:~# sudo pip3 install httplib2
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/local/lib/python3.5/dist-packages
Cleaning up...
-----------------------------------------------------------------------------------------------------------------------------
I just coped pasted everything so you can see exactly what i typed and what i am getting. --GREAT JOB ON BRING BACK BEEN WAITING ON UP DATE FOR LONG TIME>> PLEASE HELP ME I CANT WAIT TO USE AGAIN> I am not running in VM -- useing kali linux- following the instructions listed on the download page

**Comment by NovaCygni** [comment]
remove codecs from the bits near the top of the code its not needed anymore

**Comment by 5kyee** [comment]
I also get the same error messages here still don't know how to fix it and get the v3n0m running.
Can you please help?

**Comment by NovaCygni** [comment]
https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/37 Mentions your issues ;) Please update your installed Python to be the latest 3.5 version not the Kali bundled 3.4 :)
