### ISSUE TITLE
python 3.5 required

### ISSUE THREAD

**Issue by tty666** [v3n0m-Scanner/V3n0M-Scanner#37]
you should explain somewhere that python 3.5 is required because with 3.4.2 ( almost Kali 2 standard and for a lot of distrib ) it's getting a syntax error for the "async def tcp_scanner" line 439 or something like that.
So python 3.5 should be installed with "make altinstall" and "pip3.5 install <here all modules>"

Also I found a bug inside the dnsbruteforce which I fixed I will push the fix within few sec.

UPDATE : it's on the first page ... I am blind ! sorry !!!
But dnsbruteforce.py is still buggy so I keep my contribution here !

**Comment by tty666** [comment]
As I cannpot push to your project ( I am not contributor of course )
Here is the fixed changes in dnsbruteforce.py 👍 

diff V3n0M-Scanner/src/modules/dnsbrute.py ../V3n0M-Scanner/src/modules/dnsbrute.py 
8c8
< import time
---
> import time as time2
47c47
<         self.start = time.time()
---
>         self.start = time2.time()
50,52c50,52
<         seconds = int(time.strftime('%S', time.gmtime(taken)))
<         minutes = int(time.strftime('%M', time.gmtime(taken)))
<         hours = int(time.strftime('%H', time.gmtime(taken)))
---
>         seconds = int(time2.strftime('%S', time2.gmtime(taken)))
>         minutes = int(time2.strftime('%M', time2.gmtime(taken)))
>         hours = int(time2.strftime('%H', time2.gmtime(taken)))
140c140
< signal.signal(signal.SIGINT, killpid)
---
> signal(SIGINT, killpid)
173,174c173,174
< startcnt = time.time()
< progstart = time.time()
---
> startcnt = time2.time()
> progstart = time2.time()
179c179
<         progress = time.time() - progstart
---
>         progress = time2.time() - progstart
182c182
<             token = time.time() - startcnt
---
>             token = time2.time() - startcnt
188c188
<                     time.strftime('%H:%M:%S', time.gmtime(eta)))
---
>                     time2.strftime('%H:%M:%S', time2.gmtime(eta)))
190c190
<             progstart = time.time()
---
>             progstart = time2.time()
194c194
<     taken = time.time() - startcnt
---
>     taken = time2.time() - startcnt

**Comment by NovaCygni** [comment]
Ive added you to project feel free to make the pull request and changes as/when you feel like. :) yeh ive had a bunch of Kali users message me im going to assume they all hit the 3.4 snag ;) bad Kali... BlackArch for the win :)

**Comment by NovaCygni** [comment]
So you know aswell for future reference on Github its more common to see people "Fork" other peoples projects, make the change in your own fork version then submit a merge request from the entire fork itself, but ive just added you makes it easier on you :)
