### ISSUE TITLE
pip install signal, codecs, itertools problem

### ISSUE THREAD

**Issue by bib0943** [v3n0m-Scanner/V3n0M-Scanner#39]
[3] FTP crawler and vuln scan
[4] DNS brute
[5] Enable Tor/Proxy Support
[6] Misc Options
[0] Exit

:3
How many IP addresses do you want to scan: 1

 please make sure you have all of the following modules: asyncio, aiohttp, codecs, requests
 httplib2, signal, itertools
Error a module was not found,  'sudo pip3 install <package name>' to install

$ pip3 list

asyncio (3.4.3)
aiohttp (0.21.6)
requests (2.10.0)
httplib2 (0.9.2)

# sudo -H pip3 install codecs

Collecting codecs
  Could not find a version that satisfies the requirement codecs (from versions: )
No matching distribution found for codecs

same for  signal, itertools

how to fix this??

**Comment by NovaCygni** [comment]
if you know where you v3n0m file is open it with a editor and simply remove signal, codecs, and itertools from the "requirements" at the top.

**Comment by bib0943** [comment]
i try to do it alredy but wen i try to start give me that error:

Traceback (most recent call last):
  File "v3n0m.py", line 645, in <module>
    signal(SIGINT, killpid)
NameError: name 'signal' is not defined
root@bear:/opt/V3n0M-Scanner/src# python3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 645, in <module>
    signal(SIGINT, killpid)
NameError: name 'signal' is not defined
root@bear:/opt/V3n0M-Scanner/src# nano v3n0m.py
root@bear:/opt/V3n0M-Scanner/src# python3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 713, in <module>
    codecs.lookup('mbcs')
NameError: name 'codecs' is not defined

**Comment by bib0943** [comment]
i whish to understand why if there are that's module on the code, i can't install it whit pip. plztell to us how fix it, step by step :)

**Comment by d4op** [comment]
hey i dont want to hijack this thread, but the current version of v3n0m hangs after dorking 6 hrs. it simply doesnt make any noise. tested on many vps and local. same result. no idea why

**Comment by d4op** [comment]
and bib0943 please use python 3.5 and not 3 -> pip3.5

**Comment by bib0943** [comment]
1° the output tell:
Error a module was not found, 'sudo pip3 install ' to install

2° i also try to install the missing modules whit pip3.5 install 

bet the output not change....

also i try to delete form the top of the code as i write befoure, and i win the other error code...

**Comment by NovaCygni** [comment]
Your running python 3.5 and not 3.43 right? Sigint should be part of the sys import.

D4rk, Yeh I've spotted that bug aswell, its dependent on the domain being scanned from what I can tell, though tbh the entire dorks list is being removed anyway and replaced with submenus of dork types (so people can specify CCTV and so forth), that along with the cloudflare resolver and the debugging of these last few errors.

**Comment by bib0943** [comment]
i'm running python 3.5

**Comment by bib0943** [comment]
but in any pip (2.7,3.0,3.5) the missing module are missing

**Comment by d4op** [comment]
@NovaCygni why you call me D4rk ?  :P still d4op.

**Comment by NovaCygni** [comment]
bib0943 Theres a untested recovery menu added to  the latest version, if your having missing modules issues this should fix it for you, not had a chance to check it but any feedback would be appreciated. :+1:

**Comment by jeanru** [comment]
When I pip install codecs, it has following error:
 Could not find a version that satisfies the requirement codecs (from versions: )
No matching distribution found for codecs. I use python 2.7.13

**Comment by NovaCygni** [comment]
V3n0m is written in Python 3.6.... do read the main page of Githubs your on these things are normally pretty obvious, stated numerous times and will be one of the first things any Github will show....
