### ISSUE TITLE
enhancement dorking

### ISSUE THREAD

**Issue by d4op** [v3n0m-Scanner/V3n0M-Scanner#40]
idea for dorking modul:
- add some reverse ip / domain lookup for ranges
-> use code from theharvester (python too)

- add some afxr qry for domains
-> use code from dnsrecon

- check if target is a tld or a real domain if real domain (single target) use the modules above to get more targets for dorking and add them to the dork tld list / array of targets.

;)

**Comment by NovaCygni** [comment]
+1 Approved ideas, I get a couple weeks free this coming month anyway so I plan to start bringing some of the other features fully out, theCloudflare resolving works a treat, itll likely be the "Menu's/Options/Forks/More-Menus" release that has it in, so "Scanner" will give submenu for "Mass-scans" = sqli/xss/lfi+rfi/shells/cctv/ftp-crawling/wpress, "Specific Scans" for single url/domains. 

SQLi piping directly to sqlmap would be basic but im undecided if I should have a verbose feedback which would be slow as fuck, or un-verbose and run 10 sqlmaps vs diff sites at once... purely for those people who want to "Autofire and leave".
