### ISSUE TITLE
Module Not installed Fix

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#41]
Add python dns to except line. The reason for #39 and #36  is most likely due to not knowing to install dns. Can confuse n00bs

**Comment by kattstof** [comment]
I.e in v3n0m.py you're trying to import dns, but didnt add dns to the except: line can confuse newbs ;o

**Comment by NovaCygni** [comment]
Python Recovery Menu added as replacements for standard except/exit, uploading in a little while im proofreading code now, but ive added a recovery menu to download/install/update the needed Python modules and/or all Python3 modules systemwide with a --force-reinstall and --no-deps switches (* so it wont recompile large modules like numpty *)

**Comment by NovaCygni** [comment]
Just so you know the hotfix version has been uploaded, hopefully this issue is done!
