### ISSUE TITLE
Sorted urls are not being saved

### ISSUE THREAD

**Issue by windmillnl** [v3n0m-Scanner/V3n0M-Scanner#42]
Hi there!

First of all, thank you for this awesome script. Unfortunately I'm having a few issues:

`[+] URLS (unsorted):  7720
[+] URLS (sorted)  :  865

[1] SQLi Testing
[2] Back to main menu
`

Looks like it found 865 sorted results here, but the v3n0m-sqli.txt is still empty.
And when I start using the [1] SQLi Testing, it stops after checking like 30/40 links. It just hangs, no error what so ever. Have to Ctrl + C out of it.

Any idea what might cause this?

**Comment by NovaCygni** [comment]
Im away due a family emergency at the moment but ill be back home and free on tomorrow so ill have a look, its likely a small change in Syntax usage or something small like that, it happens every now and then. Gimme a couple days and ill have the HotFix for it uploaded.

**Comment by windmillnl** [comment]
Sorry to hear that NovaCygni, hope everything turns out ok..
And thanks man, no rush!

**Comment by NovaCygni** [comment]
Problems been identified ive also  spotted a way to easy-fix "Missing Modules" error messages aswell, im free tomorrow afternoon so ill bash in the HotFix then, the fix means ill have to kill a ugly part of the code in put in a Asyncio method so thats good news speed wise (* x40 speed improvement on checks *)... oh and XSS Checking is ready and working again so ill throw that in the public update.

**Comment by windmillnl** [comment]
Brilliant, that sounds awesome! 
Thank you so much for your continued support :) cheers!

**Comment by NovaCygni** [comment]
Sorry for the delay the hotfix has been uploaded at last, working on a little issue with the LFI/RFI/XSS checking still, but should be a bunch of updates over the next couple weeks as stuff is improved, Id love any feedback :) Ill close thread but feel free to open any new one if you feel any reason to. Thanks for your patience. 
NovaCygni
