### ISSUE TITLE
Add 'bs4' to the list of modules to install 

### ISSUE THREAD

**Issue by Snipercatz** [v3n0m-Scanner/V3n0M-Scanner#48]
It took me awhile to figure out how to run this, I kept getting the following error:

root@shadow:~/V3n0M-Scanner/src# python3 v3n0m.py 
  File "v3n0m.py", line 475
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax

I finally realized it was because I didn't have beautifulsoup4 installed.

Just a suggestion --> Add 'bs4' to this line:
"Then install these modules with pip3: sudo pip3 install dnspython3 aiohttp httplib2 socksipy-branch requests url"

Loving the scanner btw! Big shouts!! XO

**Comment by NovaCygni** [comment]
Ill add it to the launch error detection part of the program, so itll add bs4 to the modules auto installed. 
Also what revision did you get this error on? You should've be taken to a recovery menu not thrown a syntax error :/

**Comment by Snipercatz** [comment]
I just came across this scanner yesterday so it's definitely the latest version.  I might be totally off but I believe it said it was throwing a syntax error on line 163.  Again I could be totally wrong about the line number.  Once I did pip3 install bs4 it worked fine.

**Comment by NovaCygni** [comment]
Looks like it could be the firewall blocking it thinking its ddos traffic bug a couple others have mentioned, I've tried reproducing it on a few ISPs and setups but alas havnt found a way to reproduce the bug myself to start debugging it, I've a hunch it could be a headers rate limiting bug native to Asyncio, but thats what the IgnoreGet() part of the code worked passed. I've a free couple of days next week so I'll leave the Issue open to remind me to look into it.

**Comment by NovaCygni** [comment]
Note to self: add function to have a "trace back" log to all  outgoing/incoming traffic so last 3 exchange's both ways can be sent to a debug.log file...

**Comment by Snipercatz** [comment]
ok, thank you! <3

**Comment by NovaCygni** [comment]
Im curious what domain you were trying to target, you have a VERY low url hit count for the duration yourve run it for... on average you should be able to farm 20k+ urls in that time :/

**Comment by Snipercatz** [comment]
Sorry about the delay. I actually crashed my computer the other night and had to reinstall everything.  Since I have, I don't have any issues running this scanner.  Works great! I like it better than bingoo.  Very nice job!! 
BTW I figured out what threw that syntax error I was talking about before.  I was using python rather than python3.  Thanks for your help! xo
