### ISSUE TITLE
'ascii' codec can't decode byte 

### ISSUE THREAD

**Issue by rdek** [v3n0m-Scanner/V3n0M-Scanner#49]
Hi, got some issue here:

`/> sudo python3 v3n0m.py`
```Traceback (most recent call last):```
  File "v3n0m.py", line 1059, in <module>
    xsses = [line.strip() for line in open("statics/xsses", 'r')]
  File "v3n0m.py", line 1059, in <listcomp>
    xsses = [line.strip() for line in open("statics/xsses", 'r')]
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 122: ordinal not in range(128)`

`/> python3`
`Python 3.5.2+ (default, Aug  5 2016, 08:07:14)`
`[GCC 6.1.1 20160724] on linux`

**Comment by NovaCygni** [comment]
Which Linux are you running it on? Never seen that error before I'd appreciate if you could describe your setup a little so I can VM a version and try to reproduce the error myself so I can see what's going on.

**Comment by kattstof** [comment]
you're running a outdated version of v3n0m this is an old error go to python3s client.py nano into it and change everything that says ascii to utf-8 and maxheaders to 10000
