### ISSUE TITLE
Error during running Setup file

### ISSUE THREAD

**Issue by naveeny42** [v3n0m-Scanner/V3n0M-Scanner#53]
root@demo:~#python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'src/__init__.py' not found (or not a regular file)
package init file 'src/__init__.py' not found (or not a regular file)
running install_lib
byte-compiling /usr/local/lib/python2.7/dist-packages/v3n0m/v3n0m.py to v3n0m.pyc
  File "/usr/local/lib/python2.7/dist-packages/v3n0m/v3n0m.py", line 475
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax

running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/V3n0M-4.0.6.egg-info
Writing /usr/local/lib/python2.7/dist-packages/V3n0M-4.0.6.egg-info

I am facing this problem while installing

**Comment by NovaCygni** [comment]
Your running the wrong version of Python, V3n0M requires Python 3.5 at least, you appear to be running Python 2.7 ;o
