### ISSUE TITLE
ImportError: No module named 'bs4

### ISSUE THREAD

**Issue by zer0sec** [v3n0m-Scanner/V3n0M-Scanner#54]
i installed all the requirements

ython3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 33, in <module>
    import bs4
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:
i installed all the required dependencies but i still get this error
Install pip3 if you don't have it already: sudo apt-get install python3-pip
Then install these modules with pip3: sudo pip3 install dnspython3 aiohttp httplib2 socksipy-branch requests url

root@darkknight:~/V3n0M-Scanner/src# python3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 33, in <module>
    import bs4
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 41, in <module>
    logo()
  File "v3n0m.py", line 12, in logo
    print(R + "\n|----------------------------------------------------------------|")
NameError: name 'R' is not defined

**Comment by zer0sec** [comment]
i fixed it i ran the command 

sudo apt-get install python3-bs4

**Comment by d4op** [comment]
Pip3 install bs4
And may use python3.5
