### ISSUE TITLE
bugs after dorker

### ISSUE THREAD

**Issue by h1tman** [v3n0m-Scanner/V3n0M-Scanner#56]
good evening i have put 10 dorks in the dorks list.. early i got 2,000 urls saved good work..
now i add few more dorks... or even try 10 dorks and getting errors now

`←[K ←[31m| Domain: <←[31m> Has been targeted
 | Collected urls: 1117 Since start of scan
 | D0rks: 16/22 Progressed so far
 | Percent Done: 72
 | Current page no.: <20> in Cycles of 10 Page results pulled in Asyncio
 | Dork In Progress: .php?cat= buy shoes
 | Elapsed Time: 0:0:27
'clear' is not recognized as an internal or external command,
operable program or batch file.
←[31m
|----------------------------------------------------------------|
| Release Date 18/08/2016                                        |
|                                                                |
|        Proxy Enabled ←[32m [ False ] ←[31m                               |
|                                                                |
|                    _____       _____                           |
|          ←[32m         |____ |     |  _  |    ←[31m                      |
|             __   __   / /_ __ | |/' |_ _←[32m_ ___             ←[31m     |
|             \ \ / /  ←[32m \ \ '←[31m_ \|  /| | '_ ` _ \                 |
|              \ V←[32m /.___/ / | | \ |_←[31m/ / | | | | |                |
|    Official   \_/←[32m \____/|_←[31m| |_|←[32m\___/|_| |_| ←[31m|_| Release 4
9    |
|             ←[34m        NovaCygni  Architect    ←[31m                   |
|----------------------------------------------------------------|

Traceback (most recent call last):
  File "v3n0m.py", line 1166, in <module>
    fmenu()
  File "v3n0m.py", line 987, in fmenu
    fscan()
  File "v3n0m.py", line 634, in fscan
    usearch = loop.run_until_complete(search(pages_pulled_as_one))
  File "C:\Python35\lib\asyncio\base_events.py", line 387, in run_until_complet

    return future.result()
  File "C:\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "v3n0m.py", line 933, in search
    '%s:%s:%s' % (hours, minutes, seconds)))
  File "C:\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position
251: character maps to <undefined>

C:\Python35\V3n0M-Scanner\src>`

any ideas? somtimes it runs fine somtimes it just gives this error... i wanna run it over night with few k dorks once i have it working correct thanks

**Comment by d4op** [comment]
Just run the script on a Linux box. Maybe setup some Virtualbox running Ubuntu.

**Comment by NovaCygni** [comment]
This issue has returned? It happened along time ago and was simply the way windows was dealing with the encoding. MBCS encoding bypass resolved it before theres likely another solution, ill keep the bug open until its resolved again but in the mean time, start migrating to Linux yourll do yourself a favour if your struggling to even run Python tools on your Winblows distro.

**Comment by h1tman** [comment]
yes yes thank you are right.. i had to boot up my kali laptop and put it on there its awesome :)!
