### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by usmarine2141** [v3n0m-Scanner/V3n0M-Scanner#58]
When updating gives an error

 [+] checking for latest version...
 [!] [Program Debug Info] I did revision as 410 and current version as 409
 [!] a new version is available!
 [-]   revision:    410 or Higher Available
 [+] do you want to upgrade to the latest version? (y/n): y
 [+] downloading update...

 (^C)<class 'Exception'>

**Comment by NovaCygni** [comment]
Your trying to update version 409 to version 409... 410 hasn't been released yet thus, there is no update to detect.

**Comment by usmarine2141** [comment]
Ah okay
