### ISSUE TITLE
V3n0m halts if wifi is dropped

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#59]
V3n0m breaks if wifi signal drops add keep alive function during heavy scanning

**Comment by kattstof** [comment]
I.e wifi drops and auto recconnects but v3nom completly halts scanning and forces you to exit and restart scan , seems to be a new bug maybe with the search api being used considering this has only been happening to me for around a week. (Wouldve just edited the original issue post but im on mobile ;o)

**Comment by kattstof** [comment]
Possible fix (away from home atm will test tommorow morning
`import http.client
conn = http.clent.HTTPConnection(host, port)
conn.request(method, url, body, headers)`

or

`handler = urllib.request.HTTPHandler()
opener = urllib.request.build_opener(handler)
opener.addheaders = [("connection", "keep-alive"), ("Cookie", cookie_value)]
r = opener.open(url)`

**Comment by NovaCygni** [comment]
@kattstof Cheers mate, tbh ive just setup a new system and didnt backup my old Pycharm projects folder so ive got to reget it from the github anyway, I may aswell wait for you to hot fix and rebase it on that and then do the list of changes ive got to sort out. Im still waiting on a reply from the guy who did the Cloudbuster project but alas, I think hes AWOL or has outright abandoned it so I may start doing the ` if __name__ == __main__ ; ` section of the code to start outright merging cloudbusters fuctions into V3n0M and leave a bunch of Disclaimers/Credits-To stuff in it so people are aware im purely keeping a good project alive within V3n0M :)

**Comment by kattstof** [comment]
Running a heavy scan now while at work to make sure its fixed, will have the merge request up in eta 6 hrs.
