### ISSUE TITLE
ERROR - No Module named BS4

### ISSUE THREAD

**Issue by usmarine2141** [v3n0m-Scanner/V3n0M-Scanner#60]
Getting error when trying to run 
this is a fresh git clone 
followed steps to install and to run

root@testing:~/V3n0M-Scanner/src# python3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 33, in <module>
    import bs4
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 41, in <module>
    logo()
  File "v3n0m.py", line 12, in logo
    print(R + "\n|----------------------------------------------------------------|")
NameError: name 'R' is not defined

**Comment by kattstof** [comment]
Hmm latest gitclone for me is working minus a keepalive bug im working on , update python or download an earlier commit, or simply wait a few hours until i get home and wait till i submit a merge request.

**Comment by kattstof** [comment]
Btw u need to install bs4 using pip3

**Comment by usmarine2141** [comment]
Ha that's prolly why. my bad ill try and report back . sorry!

**Comment by kattstof** [comment]
I  came across this issue while reinstalling blackarch , `sudo pip3 install `requests fixed it for me.``

**Comment by NovaCygni** [comment]
??? Recovery menu shouldve kicked in and detected this issue itself? You running the latest version?

**Comment by kattstof** [comment]
Try sudo pip3 install BeatifulSoup4 instead of bs4  ,  i got the R not defined error but fixed by adding requests to  recovery menu.

**Comment by kattstof** [comment]
Ahh if hes running ubuntu it couod be because ubuntu has beautifulsoup packaged in, that case use 
sudo apt-get install python3-bs4
