### ISSUE TITLE
Self update still not fixed

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#63]
Self uodater sees the update but autoexits while trying to download

**Comment by NovaCygni** [comment]
Yeh I figured it might need abit more work :/ Ill have a tinkle at it later today when I sort out the OS_Detection and separate the recovery menu into its own function so it can be called from the Misc menu.

**Comment by kattstof** [comment]
Yeh, im fairly new to python im using this as a jump off point tbh,  im actually baffled by why it autoexits  im thinking something wrong with the OSdetection but not sure
