### ISSUE TITLE
NameError: name 'R' is not defined?

### ISSUE THREAD

**Issue by Piero-Bird** [v3n0m-Scanner/V3n0M-Scanner#64]
I got everything working here, however it's saying that error when I try running the program.

I'm on Kali Linux, here's the Console Output:

root@kali:/V3n0M-Scanner/src# python3 v3n0m.py
Traceback (most recent call last):
  File "v3n0m.py", line 30, in <module>
    import re, random, threading, socket, urllib.request, urllib.error, urllib.parse, http.cookiejar, subprocess, \
ImportError: No module named 'socks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 41, in <module>
    logo()
  File "v3n0m.py", line 12, in logo
    print(R + "\n|----------------------------------------------------------------|")
NameError: name 'R' is not defined

**Comment by NovaCygni** [comment]
Ahhhh I think i just spotted whats going on, the recovery menu is supposed to kick in (* Your missing some python packages *) but invoking the logo causes the recovery menu never to appear... No matter ill hotfix it in a minute. 
Please make sure your running Python 3.5.2 at least:
`python --version` to find out what version your running.
So you know to install the missing python modules you may wish to run the following commands:
`        sudo pip3 install dns --upgrade
         sudo pip3 install aiohttp --upgrade
         sudo pip3 install asyncio --upgrade
         sudo pip3 install bs4 --upgrade
         sudo pip3 install dnspython --upgrade
         sudo pip3 install datetime --upgrade
         sudo pip3 install requests --upgrade
         sudo pip3 install socksipy-branch --upgrade
         sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U `

**Comment by NovaCygni** [comment]
Hotfixed, Recovery Menu should now work fine on Kali installs with incomplete/damaged/missing Python installs and sort the issue out for you.

**Comment by Piero-Bird** [comment]
Nevermind, I was just missing a few imports

**Comment by Piero-Bird** [comment]
Thank you!

**Comment by NovaCygni** [comment]
Because of the appalling state of the bundled Python versions within Kali id strongly suggest running:
`sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo pip3 install -U` 
Yourll find there'll be at least a handful if not more Python dependencies for Packages that are very very outdated.
Ps: Make the move to Archlinux and install the BlackArch Repos ;o Kali is frankly, Only useful as a mobile USB-Toolkit-Os or a beginner Pentester/script_Kiddie OS... in my opinion... check it out you should have a good look at what your missing out on.

**Comment by NovaCygni** [comment]
Thats assuming of course you didnt just run the Recovery menu which would, sort all the possible python problems out and make sure your dependencies/packages are up to date.
