### ISSUE TITLE
v3n0m through tor - ignoring false on login

### ISSUE THREAD

**Issue by Piero-Bird** [v3n0m-Scanner/V3n0M-Scanner#65]
I don't know if this is a bug, or me making a mistake. But I have TOR running (socks5 : 127.0.0.1 : 9050)

Which works fine connecting through IRC and Firefox. However, when I try to use TOR with v3n0m it goes like so:

I choose option 5:
Requires Username/Password? Type True or False? : False

I tell it socks5, then I give it the address 127.0.0.1, and finally the port 9050.
Regardless, it asks for the "Proxy Account Username" and "Password". (if I leave blank, the main screen loads again and says "Proxy Enabled: [ False ]"

Any ideas?

**Comment by NovaCygni** [comment]
Looking at it now gimme a couple mins, its likely throwing "False" by error but I'll check it now (* Gimme 30 mins to a hour im about to have dinner *)

**Comment by NovaCygni** [comment]
my bad i spotted the problem, yeh just gonna eat dinner then ill upload the hotfix

**Comment by NovaCygni** [comment]
Hotfix uploaded problem, solved :) thanks for the bug reports :+1:

**Comment by Piero-Bird** [comment]
It still does it for me, I'll try redownloading instead of updating

**Comment by Piero-Bird** [comment]
There we go, that fixed it!

**Comment by NovaCygni** [comment]
The self-updater is broken atm as Its being re-written so I can add support for non Archlinux users, The new version of the updater should be ready in a week or so as its just going to use Pip3 to install the update for itself instead of me having to write a bunch of "If OS ==" crap for different OS's, so, Pip3 will be the way forward.

**Comment by Piero-Bird** [comment]
Sweet, I'll let you know if I run into anymore bugs. Very good stuff you guys are creating here
