### ISSUE TITLE
"Print vulnerable sites option" leads to main menu

### ISSUE THREAD

**Issue by Piero-Bird** [v3n0m-Scanner/V3n0M-Scanner#67]
Title says it all on this one. It prints out the vulnerable sites already it appears for sqli, however is there no way to write those into a file? The actual file option appears to write all of the sites it scanned, not the vulnerable ones

**Comment by NovaCygni** [comment]
The default scan mode already prints the URL to the screen so that old command is pointless atm, but will be expanded later on to add more information about the results found (* SQL type, Apache versions so forth *)
