### ISSUE TITLE
Setup.py having issues

### ISSUE THREAD

**Issue by chackokavanattu12** [v3n0m-Scanner/V3n0M-Scanner#68]
Hey Guys

I am going through the setup that you guys gave in cybrary.

Link:https://www.cybrary.it/0p3n/pentesting-scanner-sqlixsslfirfi/

I am getting the following error

root@kali:/V3n0M-Scanner# python3 setup.py
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

Please suggest how do i move forward.

**Comment by NovaCygni** [comment]
1) Use the source from the Github page not 3rd party sites that host old outdated versions
2) Use Python 3.5+ not Python 3.4 (* Your version is, Python 3.4 *)

**Comment by NovaCygni** [comment]
Hotfixed and uploaded changed setup.py file.
