### ISSUE TITLE
Custom List Check

### ISSUE THREAD

**Issue by Indeserpen** [v3n0m-Scanner/V3n0M-Scanner#70]
Hey again!

When i try to test custom list I get this error:
home/user/Desktop/samples.txt 
/root/Desktop/check.txt
Traceback (most recent call last):
  File "v3n0m.py", line 1169, in <module>
    fmenu()
  File "v3n0m.py", line 1046, in fmenu
    classicinj(url)
  File "v3n0m.py", line 255, in classicinj
    aug_url = url + "'"
TypeError: can only concatenate list (not "str") to list

**Comment by NovaCygni** [comment]
Sorry for the delay, looking into the issue now. Thanks for your patience.

**Comment by NovaCygni** [comment]
Should be fixed re-open if still doesnt work for you.
