### ISSUE TITLE
No local packages or working download links found for dns

### ISSUE THREAD

**Issue by noraj1337** [v3n0m-Scanner/V3n0M-Scanner#71]
Hi guys !

```
Reading https://pypi.python.org/simple/dns/
No local packages or working download links found for dns
error: Could not find suitable distribution for Requirement.parse('dns')
```

There is no more links avaible for `dns` on PyPi. You may want to use `dnspython` ?

**Update**: package is dead: https://pypi.python.org/pypi/dns/0.0.1

**Comment by NovaCygni** [comment]
yeh its a small issue as dnspython uses dns functions so I should probably rename it or just remove it and allow the recovery menu to install the missing dependencies itself

**Comment by noraj1337** [comment]
Ok :)
But strange to close an issue before it has been corrected ^^

**Comment by NovaCygni** [comment]
Added it to my list to do tonight, uploaded and pushed the hotfixed setup.py
