### ISSUE TITLE
Can't Install the Scanner

### ISSUE THREAD

**Issue by Shazgul** [v3n0m-Scanner/V3n0M-Scanner#74]
Getting always this error: "error: Setup script exited with error: command 'i686-linux-gnu-gcc' failed with exit status 1"

**Comment by NovaCygni** [comment]
Your problem is with your environment, Please make sure you have installed Python3.5 then try:
`sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U
`
