### ISSUE TITLE
Error while scanning

### ISSUE THREAD

**Issue by xeq** [v3n0m-Scanner/V3n0M-Scanner#75]
`Traceback (most recent call last):
  File "v3n0m.py", line 1128, in <module>
    fmenu()
  File "v3n0m.py", line 953, in fmenu
    fscan()
  File "v3n0m.py", line 636, in fscan
    usearch = loop.run_until_complete(search(pages_pulled_as_one))
  File "/usr/local/lib/python3.5/dist-packages/asyncio/base_events.py", line 296, in run_until_complete
    future = tasks.async(future, loop=self)
  File "/usr/local/lib/python3.5/dist-packages/asyncio/tasks.py", line 516, in async
    raise TypeError('A Future or coroutine is required')
TypeError: A Future or coroutine is required
sys:1: RuntimeWarning: coroutine 'search' was never awaited
`

**Comment by d4op** [comment]
I dont understand you, there is an error traceback message, just read it, understand it, fix it ….

**Comment by NovaCygni** [comment]
Hotfix uploaded.

**Comment by xeq** [comment]
Does not work help

**Comment by NovaCygni** [comment]
"Does not work help" is not remotely useful.,,,, firstly, SCREENSHOTS or error message thrown!

As stated numerous times before, Whenever posting a bug report always include the user entered values....
Ie,> Domain, searched for... after scan, which scan option was picked, Auto-Sqli or another one? So far your request for help has been vague at best.

**Comment by NovaCygni** [comment]
Tested both Auto Mode and normal mode myself... both worked fine... due to lack of information ill reclose this until it be clarified what input the user is giving.

**Comment by xeq** [comment]
https://hastebin.com/aviconokum.sql here is what you wanted

**Comment by NovaCygni** [comment]
`sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U`

**Comment by xeq** [comment]
doesn't work it's still the same ;[

**Comment by NovaCygni** [comment]
weird, have you download the main script from the Github page and tried running it from the folder? 
The autoupdate has problems still on alot of Distros it could be that meaning you have a outdated version,
` RuntimeWarning: coroutine 'search' was never awaited`
But "Search" is ----> `loop.run_until_complete(search(pages_pulled_as_one))`
Thus, "Pages pulled as one" set by you was: 20

This is exactly what should be there are you sure your Python is working/installed properly? which Distro are you running on as this error hasnt been encountered before???

**Comment by xeq** [comment]
yes.

I'm running ubuntu 16.04. This error wasn't encountered in the previous version (the one without LFI scanning I suppose, there was only SQL scan option). It happened after I've deleted the files from the old ver and upgraded to the new one via git.

**Comment by NovaCygni** [comment]
Id suggest deleting it from the system then running a search to make sure yourve not still got it somewhere, redownload the current version and try installing it again, if its still not working can you let me know if you navigate to the folder with v3n0m.py in it whether or not you can run it correctly from a terminal there with "sudo python v3n0m.py

**Comment by xeq** [comment]
yeah but why would u need root for this? (i've ran it with root and without still the same error)
i'm going to reinstall my entire OS today so we'll see.

**Comment by NovaCygni** [comment]
sudo/root for pip, dns functfions, overwriting old logs, recovery mode permissions... 

Well the error cant be reproduced and its clearly not a error within V3n0M yourself so im going to throw my 2cents in and just frankly say its either a problem with your Python setup and/or yourve not removed entirely the old version before trying again, as yourve not run the v3n0m.py file natively from the folder I cant even rule that out and despite being asked to do it yourve not, so... matter closed.

If it was something within v3n0m other people wouldve also had the same issue...

**Comment by xeq** [comment]
I've found out what caused the error - there was a process with root privileges that was messing up with random files and it has added some random chars to files. I've reinstalled the entire OS and now works fine.
