### ISSUE TITLE
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by antonely93** [v3n0m-Scanner/V3n0M-Scanner#83]
Hello,
... Install V3N0M and have this:

url/url.cpp:4:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
 #include "Python.h"
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Please how to fix?

Thanks

**Comment by NovaCygni** [comment]
No such thing as "x86_64-linux-gnu-gcc" in v3n0m, your errors nothing to do with v3n0m and reflects a overall problem with your Python installation...
