### ISSUE TITLE
Error when set Admin Page Finder

### ISSUE THREAD

**Issue by antonely93** [v3n0m-Scanner/V3n0M-Scanner#84]
Hello Guys,

I have this message when i use the option:
Traceback (most recent call last):
  File "/root/Bureau/V3n0M-Scanner-master/src/modules/adminfinder.py", line 146, in <module>
    signal.signal(signal.SIGINT, killpid)
AttributeError: 'builtin_function_or_method' object has no attribute 'signal'

How i can solve it?

Thanks

**Comment by antonely93** [comment]
this is after adding the website url

**Comment by NovaCygni** [comment]
My bad ill push the fixed update later today im at work atm :/ I see what ive done though its a simple fix.

**Comment by NovaCygni** [comment]
Pushed the fix.

**Comment by antonely93** [comment]
thinks wil try it ;)
