### ISSUE TITLE
New issue in Admin Page Finder

### ISSUE THREAD

**Issue by antonely93** [v3n0m-Scanner/V3n0M-Scanner#85]
Hello bro,
First Thank You for the fix but now i have this message after adding the target link:
/bin/sh: 1:  /root/Bureau/V3n0m-Scanner-master: not found

regards,

**Comment by NovaCygni** [comment]
:/ Doesnt appear here, and I cant seem to reproduce the error... how are you running the program? All files v3n0m requires should be within its own subfolders, if your just popping open a terminal and running the script from there have you made sure your cd'ing to the right directory before running it???

(* Really if yourve installed v3n0m via the PKGBUILD or the setup.py you shouldnt have to do anything other than type "v3n0m"... and itll work from and in any location *).

**Comment by NovaCygni** [comment]
Ill leave the bug report open for 14 days to allow feedback if any other issues arise, then ill close the bug report as, likely solved :+1:

**Comment by kattstof** [comment]
through massive hours of bug testing i cant recreate the trouble. most likely user/environment errors ;o
