### ISSUE TITLE
error when doing python3 setup.py install --user -g

### ISSUE THREAD

**Issue by livtyler** [v3n0m-Scanner/V3n0M-Scanner#86]
> Traceback (most recent call last):
>   File "setup.py", line 3, in <module>
>     import setuptools
> ImportError: No module named 'setuptools'

Using upto date rolling Kali.

Have Python 3 installed.

**Comment by NovaCygni** [comment]
`pip install setuptools`
Your python isnt installed properly, and will requires a large amount of updates once v3n0m starts ((*dont worry that part is all automated ;) *)) but this isnt your fault its Kali in general, it likes to release/ship the distro with incomplete and badly setup Python installs... If your familiar with Linux yourll likely be better of getting any Archlinux Distro and installing that instead, then you can simply upgrade it to blackarch, which, is farrrrrrrrrr superior to Kali (Feel free to compare the tools list). https://blackarch.org/
