### ISSUE TITLE
Remove duplicate dorks

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#89]
There are about 4k duplicates 
I removed dupes+ alphabetized here : https://pastebin.com/8P2NN8vm

**Comment by NovaCygni** [comment]
Well the plan was to remove the Dork list "AsIs" and split it into specialised d0rk lists... or to implement a d0rk seed-generator, to generate "Valid" d0rks on the fly though thats obviouslly, a lot of work to implement. At least if I split the d0rk lists, I can have targets of XSS/LFI, SQLi, and CCTV panels separated again which for CCTV hunting would make v3n0m viable as currently Ive removed the "Panel" checks.

**Comment by kattstof** [comment]
Well you *could still* do that but i saved you time sorting the dupes out. I figured alphabetizing would help incase you for some reason needed to look a specific dorkup in a text editor.

**Comment by NovaCygni** [comment]
Should be around a week tops and the lists will be seperated, but, Ill keep yours as the "Just fuckin scan every possible dork we can" option ;o

**Comment by d4op** [comment]
intelligent dork genrator.
1. crawl results using current dork list
2. parse every parameter like member.php?id=1&page=2
3. splits dorks like member.php?id= and member&page=
4. compares with current dork list
5. if not present, add to dork list.

like a learning mode ;)

**Comment by NovaCygni** [comment]
Funny enough thats pretty much what im doing :') Generating known d0rks on the fly, then at the end of each d0rks line in the file having another slice that can be used to count how many times the d0rk was tested with 0 results. That way "dead" d0rks can be flagged and auto-erased after x times of no responses. At the moment im back to compiling various lists atm for more specified searching id like to not have a large single "All-In-One" d0rk list not being the primary list.
