### ISSUE TITLE
setup exited with error cl.exe

### ISSUE THREAD

**Issue by asura132** [v3n0m-Scanner/V3n0M-Scanner#90]
no such file or directory keeps popping

**Comment by NovaCygni** [comment]
.exe???? Screenshot? If this is windows....install your Python3.6 properly :)

**Comment by kattstof** [comment]
please copy pasta the full error that your terminal is throwing plox also remember, if you're running winblows (which you shouldnt for opsec reasons) that you typically have to add pip to your PATH and pip -m to install dependencies

**Comment by asura132** [comment]
``Running url-0.4.1\setup.py -q bdist_egg --dist-dir C:\Users\user\AppData\Local\T
emp\easy_install-nizl33zd\url-0.4.1\egg-dist-tmp-cuxkem4w
Building from C++
error: Setup script exited with error: command 'cl.exe' failed: No such file or
directory

**Comment by kattstof** [comment]
If you're running winblows you really shouldn't be running the setup script just cd into v3n0m and pip all the dependencies then python v3n0m.py

**Comment by asura132** [comment]
oh okay imma do it right now

**Comment by kattstof** [comment]
(its mainly due with how winblows uses python) ie winblows=pip -m linux (and crapple) = pip3
