### ISSUE TITLE
Running Scanner

### ISSUE THREAD

**Issue by lucciisgithub** [v3n0m-Scanner/V3n0M-Scanner#92]
How do you run the scanner? theres no instructions.

**Comment by d4op** [comment]
lol, Python v3n0m.py

Von meinem iPhone gesendet

Am 17.05.2017 um 23:58 schrieb Luciano Scarpaci <notifications@github.com<mailto:notifications@github.com>>:


How do you run the scanner? theres no instructions.

**Comment by lucciisgithub** [comment]
Where does the v3n0m.py go after it is compiled? i see it in the src directory but when i run it i get errors so that is not the right directory i guess

**Comment by lucciisgithub** [comment]
Also when i run this command: $ python3 setup.py install --user what exactly happens? and where does the v3n0m.py go?

**Comment by lucciisgithub** [comment]
OK i figured it out it. it was in the src/ directory and i had to run python3 v3n0m.py
