### ISSUE TITLE
(MacOS) V3n0m 

### ISSUE THREAD

**Issue by Arkanix** [v3n0m-Scanner/V3n0M-Scanner#94]
Hi

Problem for execut : `python3 setup.py install --user`

Error : 

url/url-cpp/src/url.cpp:4:10: fatal error: 'unordered_map' file not found
#include <unordered_map>
         ^
1 error generated.
error: Setup script exited with error: command '/usr/bin/clang' failed with exit status 1

thx

**Comment by NovaCygni** [comment]
https://stackoverflow.com/questions/7572429/mac-osx-python-packages-failed-to-build-because-of-gcc-issues
Not a V3n0m Issue its a problem with your Python install, follow that thread :+1:
