### ISSUE TITLE
Add Docker image

### ISSUE THREAD

**Issue by madnight** [v3n0m-Scanner/V3n0M-Scanner#95]

**Comment by NovaCygni** [comment]
Not quite sure why someone would want one but then tbh ive not spent any time playing around with Docker :/ Your welcome to fork and pull-request it if you wish to do it yourself though.

**Comment by madnight** [comment]
I would like to see an simple instant setup and start with docker like this project https://github.com/1N3/Sn1per which can be started by just `docker run --rm -ti menzo/sn1per-docker sniper menzo.io` Given some time i'll look what i can do, creating a docker image is realtivley simple in most cases.
