### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Box365** [v3n0m-Scanner/V3n0M-Scanner#98]
build\temp.win32-2.7\Release\url/url-cpp/src\url.pyd.manifest : general error c1010070: Failed to load and parse the manifest. The system cannot find the file specified.
error: Setup script exited with error: command 'mt.exe' failed with exit status 31

can anyone help ?

**Comment by kattstof** [comment]
You're using windows? don't use the setup script. just cd into the v3n0m directory and python all the things.

**Comment by Box365** [comment]
been trying that but i just get errors with that aswell,

`  File "C:\Python36\v3n0m\src\v3n0m.py", line 595
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax`

**Comment by NovaCygni** [comment]
try adding 3 to the "python" command, ie, python3 C:\Python36\v3n0m\src\v3n0m.py
;)

**Comment by Box365** [comment]
that is with the python command added 

`C:\Users\user>cd C:\Python36\v3n0m

C:\Python36\v3n0m>python v3n0m.py
  File "v3n0m.py", line 595
    print("[+] Testing: ", end=' ')
                              ^
SyntaxError: invalid syntax

C:\Python36\v3n0m>`

**Comment by d4op** [comment]
Use a Linux env or use a docker Version of v3n0m

Von meinem iPad gesendet

Am 03.08.2017 um 21:30 schrieb Box365 <notifications@github.com<mailto:notifications@github.com>>:


new to python but keep getting this error on installing

`V3n0M 416 is already the active version in easy-install.pth

Installed c:\users\user\appdata\roaming\python\python27\site-packages\v3n0m-416-py2.7.egg
Processing dependencies for V3n0M==416
Searching for url
Reading http://pypi.python.org/simple/url/
Best match: url 0.4.1
Downloading https://pypi.python.org/packages/6f/13/6cc8556dae2a1ffc04fac35ada439b726ff9858dd7a69e2c4d0b9e1f0267/url-0.4.1.tar.gz#md5=f76247d694f5c93d602888613da1f92a
Processing url-0.4.1.tar.gz
Running url-0.4.1\setup.py -q bdist_egg --dist-dir c:\users\user\appdata\local\temp\easy_install-zuzqup\url-0.4.1\egg-dist-tmp-edq_el
Building from C++
error: Setup script exited with error: Unable to find vcvarsall.bat
`

can anyone help me out?

**Comment by kattstof** [comment]
Sounds like he hasnt added python3 to his PATH but it being winblows it shouldnt be a worry
All i can say is v3n0m works on my windblows 7 vm so you're doing something wrong with your enviromemt

_Sent from my Lge LG-M150 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
